import { contextBridge, ipcRenderer } from 'electron';
import type { TelegramForumTopicContext } from '../src/models/telegram';

// Expose typed API to renderer
contextBridge.exposeInMainWorld('electronAPI', {
  // ─── Platform info ──────────────────────────────────────────────
  platform: process.platform,  // 'darwin' | 'win32' | 'linux'

  // ─── Window Controls ─────────────────────────────────────────────
  window: {
    minimize: () => ipcRenderer.send('window:minimize'),
    maximize: () => ipcRenderer.send('window:maximize'),
    close: () => ipcRenderer.send('window:close'),
    quit: () => ipcRenderer.send('window:quit'),
    isMaximized: () => ipcRenderer.invoke('window:isMaximized'),
  },

  // ─── Shell ───────────────────────────────────────────────────────
  shell: {
    openExternal: (url: string) => ipcRenderer.send('shell:openExternal', url),
    openPath: (filePath: string) => ipcRenderer.invoke('shell:openPath', filePath),
    openInApp: (url: string) => ipcRenderer.invoke('shell:openInApp', url),
  },

  // ─── Util ───────────────────────────────────────────────────────
  util: {
    fetchUrl: (args: { url: string }) => ipcRenderer.invoke('util:fetchUrl', args),
  },

  // ─── Login / Account ─────────────────────────────────────────────
  login: {
    loginQR: (tempId: string, proxyId?: number | null) => ipcRenderer.invoke('login:qr', { tempId, proxyId }),
    loginQRAbort: (tempId: string) => ipcRenderer.invoke('login:qr:abort', { tempId }),
    loginCookies: (imei: string, cookies: string, userAgent: string) =>
      ipcRenderer.invoke('login:cookies', { imei, cookies, userAgent }),
    loginAuth: (authJson: string, proxyId?: number | null) => ipcRenderer.invoke('login:auth', { authJson, proxyId }),
    openZaloWebviewLogin: (proxyId?: number | null) => ipcRenderer.invoke('login:openZaloWebview', proxyId),
    connectAccount: (auth: any) => ipcRenderer.invoke('login:connect', { auth }),
    disconnectAccount: (zaloId: string) => ipcRenderer.invoke('login:disconnect', { zaloId }),
    disconnectAll: () => ipcRenderer.invoke('login:disconnectAll'),
    getAccounts: () => ipcRenderer.invoke('login:getAccounts'),
    removeAccount: (zaloId: string, deleteData?: boolean) => ipcRenderer.invoke('login:removeAccount', { zaloId, deleteData }),
    getMediaAutoDelete: (zaloId: string) => ipcRenderer.invoke('login:getMediaAutoDelete', { zaloId }),
    setMediaAutoDelete: (zaloId: string, enabled: boolean, days: number) => ipcRenderer.invoke('login:setMediaAutoDelete', { zaloId, enabled, days }),
    runAllMediaCleanup: () => ipcRenderer.invoke('login:runAllMediaCleanup'),
    checkHealth: (zaloIds: string | string[]) => ipcRenderer.invoke('login:checkHealth', { zaloIds }),
    checkAndRefreshAvatar: (zaloId: string) => ipcRenderer.invoke('login:checkAndRefreshAvatar', { zaloId }),
    requestOldMessages: (zaloId: string) => ipcRenderer.invoke('login:requestOldMessages', { zaloId }),
  },

  // ─── Zalo API ────────────────────────────────────────────────────
  zalo: {
    sendMessage: (params: any) => ipcRenderer.invoke('zalo:sendMessage', params),
    sendImage: (params: any) => ipcRenderer.invoke('zalo:sendImage', params),
    sendImages: (params: any) => ipcRenderer.invoke('zalo:sendImages', params),
    sendFile: (params: any) => ipcRenderer.invoke('zalo:sendFile', params),
    sendSticker: (params: any) => ipcRenderer.invoke('zalo:sendSticker', params),
    sendVoice: (params: any) => ipcRenderer.invoke('zalo:sendVoice', params),
    sendVideo: (params: any) => ipcRenderer.invoke('zalo:sendVideo', params),
    sendLink: (params: any) => ipcRenderer.invoke('zalo:sendLink', params),
    sendCard: (params: any) => ipcRenderer.invoke('zalo:sendCard', params),
    undoMessage: (params: any) => ipcRenderer.invoke('zalo:undoMessage', params),
    deleteMessage: (params: any) => ipcRenderer.invoke('zalo:deleteMessage', params),
    deleteChat: (params: any) => ipcRenderer.invoke('zalo:deleteChat', params),
    addReaction: (params: any) => ipcRenderer.invoke('zalo:addReaction', params),
    forwardMessage: (params: any) => ipcRenderer.invoke('zalo:forwardMessage', params),
    getFriends: (auth: any) => ipcRenderer.invoke('zalo:getFriends', { auth }),
    getGroups: (auth: any) => ipcRenderer.invoke('zalo:getGroups', { auth }),
    getUserInfo: (params: any) => ipcRenderer.invoke('zalo:getUserInfo', params),
    getContext: (params: any) => ipcRenderer.invoke('zalo:getContext', params),
    findUser: (params: any) => ipcRenderer.invoke('zalo:findUser', params),
    sendFriendRequest: (params: any) => ipcRenderer.invoke('zalo:sendFriendRequest', params),
    acceptFriendRequest: (params: any) => ipcRenderer.invoke('zalo:acceptFriendRequest', params),
    rejectFriendRequest: (params: any) => ipcRenderer.invoke('zalo:rejectFriendRequest', params),
    undoFriendRequest: (params: any) => ipcRenderer.invoke('zalo:undoFriendRequest', params),
    removeFriend: (params: any) => ipcRenderer.invoke('zalo:removeFriend', params),
    getSentFriendRequests: (auth: any) => ipcRenderer.invoke('zalo:getSentFriendRequests', { auth }),
    getFriendRequestStatus: (params: any) => ipcRenderer.invoke('zalo:getFriendRequestStatus', params),
    getFriendRecommendations: (auth: any) => ipcRenderer.invoke('zalo:getFriendRecommendations', { auth }),
    getAliasList: (params: any) => ipcRenderer.invoke('zalo:getAliasList', params),
    blockUser: (params: any) => ipcRenderer.invoke('zalo:blockUser', params),
    unblockUser: (params: any) => ipcRenderer.invoke('zalo:unblockUser', params),
    getRelatedFriendGroup: (params: any) => ipcRenderer.invoke('zalo:getRelatedFriendGroup', params),
    createGroup: (params: any) => ipcRenderer.invoke('zalo:createGroup', params),
    getGroupInfo: (params: any) => ipcRenderer.invoke('zalo:getGroupInfo', params),
    addUserToGroup: (params: any) => ipcRenderer.invoke('zalo:addUserToGroup', params),
    removeUserFromGroup: (params: any) => ipcRenderer.invoke('zalo:removeUserFromGroup', params),
    leaveGroup: (params: any) => ipcRenderer.invoke('zalo:leaveGroup', params),
    changeGroupName: (params: any) => ipcRenderer.invoke('zalo:changeGroupName', params),
    changeGroupAvatar: (params: any) => ipcRenderer.invoke('zalo:changeGroupAvatar', params),
    changeGroupOwner: (params: any) => ipcRenderer.invoke('zalo:changeGroupOwner', params),
    disperseGroup: (params: any) => ipcRenderer.invoke('zalo:disperseGroup', params),
    addGroupDeputy: (params: any) => ipcRenderer.invoke('zalo:addGroupDeputy', params),
    removeGroupDeputy: (params: any) => ipcRenderer.invoke('zalo:removeGroupDeputy', params),
    getGroupMembersInfo: (params: any) => ipcRenderer.invoke('zalo:getGroupMembersInfo', params),
    addGroupBlockedMember: (params: any) => ipcRenderer.invoke('zalo:addGroupBlockedMember', params),
    removeGroupBlockedMember: (params: any) => ipcRenderer.invoke('zalo:removeGroupBlockedMember', params),
    getGroupBlockedMember: (params: any) => ipcRenderer.invoke('zalo:getGroupBlockedMember', params),
    inviteUserToGroups: (params: any) => ipcRenderer.invoke('zalo:inviteUserToGroups', params),
    updateGroupSettings: (params: any) => ipcRenderer.invoke('zalo:updateGroupSettings', params),
    getGroupLinkDetail: (params: any) => ipcRenderer.invoke('zalo:getGroupLinkDetail', params),
    getGroupLinkInfo: (params: any) => ipcRenderer.invoke('zalo:getGroupLinkInfo', params),
    joinGroupLink: (params: any) => ipcRenderer.invoke('zalo:joinGroupLink', params),
    enableGroupLink: (params: any) => ipcRenderer.invoke('zalo:enableGroupLink', params),
    disableGroupLink: (params: any) => ipcRenderer.invoke('zalo:disableGroupLink', params),
    getPendingGroupMembers: (params: any) => ipcRenderer.invoke('zalo:getPendingGroupMembers', params),
    reviewPendingMemberRequest: (params: any) => ipcRenderer.invoke('zalo:reviewPendingMemberRequest', params),
    getMessageHistory: (params: any) => ipcRenderer.invoke('zalo:getMessageHistory', params),
    getGroupChatHistory: (params: any) => ipcRenderer.invoke('zalo:getGroupChatHistory', params),
    getPinConversations: (auth: any) => ipcRenderer.invoke('zalo:getPinConversations', { auth }),
    setPinConversation: (params: any) => ipcRenderer.invoke('zalo:setPinConversation', params),
    setMute: (params: any) => ipcRenderer.invoke('zalo:setMute', params),
    keepAlive: (auth: any) => ipcRenderer.invoke('zalo:keepAlive', { auth }),
    getLabels: (params: any) => ipcRenderer.invoke('zalo:getLabels', params),
    updateLabels: (params: any) => ipcRenderer.invoke('zalo:updateLabels', params),
    changeFriendAlias: (params: any) => ipcRenderer.invoke('zalo:changeFriendAlias', params),
    getStickers: (params: any) => ipcRenderer.invoke('zalo:getStickers', params),
    getStickersDetail: (params: any) => ipcRenderer.invoke('zalo:getStickersDetail', params),
    getStickerCategoryDetail: (params: any) => ipcRenderer.invoke('zalo:getStickerCategoryDetail', params),
    addUnreadMark: (params: any) => ipcRenderer.invoke('zalo:addUnreadMark', params),
    removeUnreadMark: (params: any) => ipcRenderer.invoke('zalo:removeUnreadMark', params),
    createPoll: (params: any) => ipcRenderer.invoke('zalo:createPoll', params),
    getPollDetail: (params: any) => ipcRenderer.invoke('zalo:getPollDetail', params),
    lockPoll: (params: any) => ipcRenderer.invoke('zalo:lockPoll', params),
    doVotePoll: (params: any) => ipcRenderer.invoke('zalo:doVotePoll', params),
    addPollOption: (params: any) => ipcRenderer.invoke('zalo:addPollOption', params),
    uploadVideoThumb: (params: any) => ipcRenderer.invoke('zalo:uploadVideoThumb', params),
    uploadVideoFile: (params: any) => ipcRenderer.invoke('zalo:uploadVideoFile', params),
    uploadVoiceFile: (params: any) => ipcRenderer.invoke('zalo:uploadVoiceFile', params),
    getQuickMessageList: (params: any) => ipcRenderer.invoke('zalo:getQuickMessageList', params),
    addQuickMessage: (params: any) => ipcRenderer.invoke('zalo:addQuickMessage', params),
    updateQuickMessage: (params: any) => ipcRenderer.invoke('zalo:updateQuickMessage', params),
    removeQuickMessage: (params: any) => ipcRenderer.invoke('zalo:removeQuickMessage', params),
    createNote: (params: any) => ipcRenderer.invoke('zalo:createNote', params),
    editNote: (params: any) => ipcRenderer.invoke('zalo:editNote', params),
    createReminder: (params: any) => ipcRenderer.invoke('zalo:createReminder', params),
    editReminder: (params: any) => ipcRenderer.invoke('zalo:editReminder', params),
    removeReminder: (params: any) => ipcRenderer.invoke('zalo:removeReminder', params),
    getListReminder: (params: any) => ipcRenderer.invoke('zalo:getListReminder', params),
    getReminder: (params: any) => ipcRenderer.invoke('zalo:getReminder', params),
    sendSeenEvent: (params: any) => ipcRenderer.invoke('zalo:sendSeenEvent', params),
    sendBankCard: (params: any) => ipcRenderer.invoke('zalo:sendBankCard', params),
  },

    db: {
    getMessages: (params: any) => ipcRenderer.invoke('db:getMessages', params),
    getMessagesAround: (params: any) => ipcRenderer.invoke('db:getMessagesAround', params),
    getContacts: (zaloId: string) => ipcRenderer.invoke('db:getContacts', { zaloId }),
    getContactsFiltered: (params: any) => ipcRenderer.invoke('db:getContactsFiltered', params),
    saveAccount: (account: any) => ipcRenderer.invoke('db:saveAccount', account),
    searchContactByPhone: (params: { zaloId: string; phone: string }) => ipcRenderer.invoke('db:searchContactByPhone', params),
    searchMessages: (params: any) => ipcRenderer.invoke('db:searchMessages', params),
    getMediaMessages: (params: any) => ipcRenderer.invoke('db:getMediaMessages', params),
    getFileMessages: (params: any) => ipcRenderer.invoke('db:getFileMessages', params),
    getUnreadCount: (zaloId: string) => ipcRenderer.invoke('db:getUnreadCount', { zaloId }),
    markAsRead: (params: any) => ipcRenderer.invoke('db:markAsRead', params),
    markMessageRecalled: (params: any) => ipcRenderer.invoke('db:markMessageRecalled', params),
    deleteMessages: (params: any) => ipcRenderer.invoke('db:deleteMessages', params),
    updateContactProfile: (params: any) => ipcRenderer.invoke('db:updateContactProfile', params),
    updateAccountPhone: (params: any) => ipcRenderer.invoke('db:updateAccountPhone', params),
    updateReaction: (params: any) => ipcRenderer.invoke('db:updateReaction', params),
    updateLocalPaths: (params: any) => ipcRenderer.invoke('db:updateLocalPaths', params),
    getMessageById: (params: any) => ipcRenderer.invoke('db:getMessageById', params),
    getMessagesByIds: (params: any) => ipcRenderer.invoke('db:getMessagesByIds', params),
    getStoragePath: () => ipcRenderer.invoke('db:getStoragePath'),
    setStoragePath: (params: any) => ipcRenderer.invoke('db:setStoragePath', params),
    selectStorageFolder: () => ipcRenderer.invoke('db:selectStorageFolder'),
    getFriends: (params: any) => ipcRenderer.invoke('db:getFriends', params),
    saveFriends: (params: any) => ipcRenderer.invoke('db:saveFriends', params),
    isFriend: (params: any) => ipcRenderer.invoke('db:isFriend', params),
    getFriendRequests: (params: any) => ipcRenderer.invoke('db:getFriendRequests', params),
    saveFriendRequests: (params: any) => ipcRenderer.invoke('db:saveFriendRequests', params),
    upsertFriendRequest: (params: any) => ipcRenderer.invoke('db:upsertFriendRequest', params),
    removeFriendRequest: (params: any) => ipcRenderer.invoke('db:removeFriendRequest', params),
    addFriend: (params: any) => ipcRenderer.invoke('db:addFriend', params),
    removeFriend: (params: any) => ipcRenderer.invoke('db:removeFriend', params),
    deleteConversation: (params: any) => ipcRenderer.invoke('db:deleteConversation', params),
    getLinks: (params: any) => ipcRenderer.invoke('db:getLinks', params),
    saveLink: (params: any) => ipcRenderer.invoke('db:saveLink', params),
    getGroupMembers: (params: any) => ipcRenderer.invoke('db:getGroupMembers', params),
    getAllGroupMembers: (params: any) => ipcRenderer.invoke('db:getAllGroupMembers', params),
    saveGroupMembers: (params: any) => ipcRenderer.invoke('db:saveGroupMembers', params),
    upsertGroupMember: (params: any) => ipcRenderer.invoke('db:upsertGroupMember', params),
    removeGroupMember: (params: any) => ipcRenderer.invoke('db:removeGroupMember', params),
    saveStickers: (params: any) => ipcRenderer.invoke('db:saveStickers', params),
    getStickerById: (params: any) => ipcRenderer.invoke('db:getStickerById', params),
    getRecentStickers: (params?: any) => ipcRenderer.invoke('db:getRecentStickers', params || {}),
    addRecentSticker: (params: any) => ipcRenderer.invoke('db:addRecentSticker', params),
    markStickerUnsupported: (params: any) => ipcRenderer.invoke('db:markStickerUnsupported', params),
    saveStickerPacks: (params: any) => ipcRenderer.invoke('db:saveStickerPacks', params),
    getStickerPacks: (params?: any) => ipcRenderer.invoke('db:getStickerPacks', params || {}),
    getStickersByPackId: (params: any) => ipcRenderer.invoke('db:getStickersByPackId', params),
    saveKeywordStickers: (params: any) => ipcRenderer.invoke('db:saveKeywordStickers', params),
    getKeywordStickers: (params: any) => ipcRenderer.invoke('db:getKeywordStickers', params),
    getStickersByIds: (params: any) => ipcRenderer.invoke('db:getStickersByIds', params),
    getAllCachedPackSummaries: (params?: any) => ipcRenderer.invoke('db:getAllCachedPackSummaries', params || {}),
    getPinnedMessages: (params: any) => ipcRenderer.invoke('db:getPinnedMessages', params),
    getMessagesByType: (params: any) => ipcRenderer.invoke('db:getMessagesByType', params),
    pinMessage: (params: any) => ipcRenderer.invoke('db:pinMessage', params),
    unpinMessage: (params: any) => ipcRenderer.invoke('db:unpinMessage', params),
    bringPinnedToTop: (params: any) => ipcRenderer.invoke('db:bringPinnedToTop', params),
    getLocalQuickMessages: (params: any) => ipcRenderer.invoke('db:getLocalQuickMessages', params),
    upsertLocalQuickMessage: (params: any) => ipcRenderer.invoke('db:upsertLocalQuickMessage', params),
    deleteLocalQuickMessage: (params: any) => ipcRenderer.invoke('db:deleteLocalQuickMessage', params),
    bulkReplaceLocalQuickMessages: (params: any) => ipcRenderer.invoke('db:bulkReplaceLocalQuickMessages', params),
    getAllLocalQuickMessages: () => ipcRenderer.invoke('db:getAllLocalQuickMessages'),
    cloneLocalQuickMessages: (params: any) => ipcRenderer.invoke('db:cloneLocalQuickMessages', params),
    setLocalQMActive: (params: any) => ipcRenderer.invoke('db:setLocalQMActive', params),
    setLocalQMOrder: (params: any) => ipcRenderer.invoke('db:setLocalQMOrder', params),

    // Local Labels
    getLocalLabels: (params: any) => ipcRenderer.invoke('db:getLocalLabels', params),
    upsertLocalLabel: (params: any) => ipcRenderer.invoke('db:upsertLocalLabel', params),
    deleteLocalLabel: (params: any) => ipcRenderer.invoke('db:deleteLocalLabel', params),
    cloneLocalLabels: (params: any) => ipcRenderer.invoke('db:cloneLocalLabels', params),
    getLocalLabelThreads: (params: any) => ipcRenderer.invoke('db:getLocalLabelThreads', params),
    assignLocalLabelToThread: (params: any) => ipcRenderer.invoke('db:assignLocalLabelToThread', params),
    bulkAssignLocalLabelToThread: (params: any) => ipcRenderer.invoke('db:bulkAssignLocalLabelToThread', params),
    removeLocalLabelFromThread: (params: any) => ipcRenderer.invoke('db:removeLocalLabelFromThread', params),
    getThreadLocalLabels: (params: any) => ipcRenderer.invoke('db:getThreadLocalLabels', params),
    setLocalLabelActive: (params: any) => ipcRenderer.invoke('db:setLocalLabelActive', params),
    setLocalLabelOrder: (params: any) => ipcRenderer.invoke('db:setLocalLabelOrder', params),
    getNotifSettings: (zaloId: string) => ipcRenderer.invoke('db:getNotifSettings', { zaloId }),
    setNotifSettings: (params: any) => ipcRenderer.invoke('db:setNotifSettings', params),

    setContactFlags: (params: any) => ipcRenderer.invoke('db:setContactFlags', params),
    getContactsWithFlags: (params: any) => ipcRenderer.invoke('db:getContactsWithFlags', params),
    setContactAlias: (params: any) => ipcRenderer.invoke('db:setContactAlias', params),

    // Message Drafts
    upsertDraft: (params: any) => ipcRenderer.invoke('db:upsertDraft', params),
    deleteDraft: (params: any) => ipcRenderer.invoke('db:deleteDraft', params),
    getDraft: (params: any) => ipcRenderer.invoke('db:getDraft', params),
    getDrafts: (params: any) => ipcRenderer.invoke('db:getDrafts', params),
    deleteOldDrafts: (params?: any) => ipcRenderer.invoke('db:deleteOldDrafts', params || {}),

    // Bank Cards
    getBankCards: (params: any) => ipcRenderer.invoke('db:getBankCards', params),
    upsertBankCard: (params: any) => ipcRenderer.invoke('db:upsertBankCard', params),
    deleteBankCard: (params: any) => ipcRenderer.invoke('db:deleteBankCard', params),

    // Local Pinned Conversations
    getLocalPinnedConversations: (params: any) => ipcRenderer.invoke('db:getLocalPinnedConversations', params),
    setLocalPinnedConversation: (params: any) => ipcRenderer.invoke('db:setLocalPinnedConversation', params),
  },

  // ─── CRM ─────────────────────────────────────────────────────────
  crm: {
    getNotes: (params: any) => ipcRenderer.invoke('crm:getNotes', params),
    saveNote: (params: any) => ipcRenderer.invoke('crm:saveNote', params),
    deleteNote: (params: any) => ipcRenderer.invoke('crm:deleteNote', params),
    getContacts: (params: any) => ipcRenderer.invoke('crm:getContacts', params),
    getContactStats: (params: any) => ipcRenderer.invoke('crm:getContactStats', params),
    getCampaigns: (params: any) => ipcRenderer.invoke('crm:getCampaigns', params),
    saveCampaign: (params: any) => ipcRenderer.invoke('crm:saveCampaign', params),
    deleteCampaign: (params: any) => ipcRenderer.invoke('crm:deleteCampaign', params),
    cloneCampaign: (params: any) => ipcRenderer.invoke('crm:cloneCampaign', params),
    updateCampaignStatus: (params: any) => ipcRenderer.invoke('crm:updateCampaignStatus', params),
    addCampaignContacts: (params: any) => ipcRenderer.invoke('crm:addCampaignContacts', params),
    getCampaignContacts: (params: any) => ipcRenderer.invoke('crm:getCampaignContacts', params),
    getSendLog: (params: any) => ipcRenderer.invoke('crm:getSendLog', params),
    getQueueStatus: (params: any) => ipcRenderer.invoke('crm:getQueueStatus', params),
    getCampaignStats: (params: any) => ipcRenderer.invoke('crm:getCampaignStats', params),
    getActivityStats: (params: any) => ipcRenderer.invoke('crm:getActivityStats', params),
  },

  // ─── Analytics / Reporting ──────────────────────────────────────────
  analytics: {
    dashboardOverview:   (params: any) => ipcRenderer.invoke('analytics:dashboardOverview', params),
    messageVolume:       (params: any) => ipcRenderer.invoke('analytics:messageVolume', params),
    peakHours:           (params: any) => ipcRenderer.invoke('analytics:peakHours', params),
    contactGrowth:       (params: any) => ipcRenderer.invoke('analytics:contactGrowth', params),
    contactSegmentation: (params: any) => ipcRenderer.invoke('analytics:contactSegmentation', params),
    campaignComparison:  (params: any) => ipcRenderer.invoke('analytics:campaignComparison', params),
    friendRequests:      (params: any) => ipcRenderer.invoke('analytics:friendRequests', params),
    workflowAnalytics:   (params: any) => ipcRenderer.invoke('analytics:workflowAnalytics', params),
    aiAnalytics:         (params: any) => ipcRenderer.invoke('analytics:aiAnalytics', params),
    responseTime:        (params: any) => ipcRenderer.invoke('analytics:responseTime', params),
    labelUsage:          (params: any) => ipcRenderer.invoke('analytics:labelUsage', params),
  },

  // ─── File ────────────────────────────────────────────────────────
  file: {
    openDialog: (options: any) => ipcRenderer.invoke('file:openDialog', options),
    saveImage: (params: any) => ipcRenderer.invoke('file:saveImage', params),
    getAppDataPath: () => ipcRenderer.invoke('file:getAppDataPath'),
    openPath: (filePath: string) => ipcRenderer.invoke('file:openPath', filePath),
    showItemInFolder: (filePath: string) => ipcRenderer.invoke('file:showItemInFolder', filePath),
    saveAs: (params: any) => ipcRenderer.invoke('file:saveAs', params),
    saveTempBlob: (params: any) => ipcRenderer.invoke('file:saveTempBlob', params),
    getVideoMeta: (params: any) => ipcRenderer.invoke('file:getVideoMeta', params),
    readImageAsBase64: (params: { localPath?: string; remoteUrl?: string }) => ipcRenderer.invoke('file:readImageAsBase64', params),
    repairImage: (params: any) => ipcRenderer.invoke('file:repairImage', params),
    validateLocalImages: (items: any) => ipcRenderer.invoke('file:validateLocalImages', items),
    captureScreenshot: () => ipcRenderer.invoke('file:captureScreenshot'),
    resolveMediaUrl: (bossUrl: string, mediaType?: string) => ipcRenderer.invoke('media:resolveUrl', { bossUrl, mediaType }),
    hasMediaCache: (bossUrl: string) => ipcRenderer.invoke('media:hasCache', { bossUrl }),
    preloadMediaBatch: (urls: string[]) => ipcRenderer.invoke('media:preloadBatch', { urls }),
    ensureMediaLocal: (bossUrl: string, mediaType?: string) => ipcRenderer.invoke('file:employeeEnsureMediaLocal', { bossUrl, mediaType }),
  },


  // ─── Workflow Engine ─────────────────────────────────────────────
    workflow: {
      list: () => ipcRenderer.invoke('workflow:list'),
      get: (id: string) => ipcRenderer.invoke('workflow:get', { id }),
      save: (workflow: any) => ipcRenderer.invoke('workflow:save', { workflow }),
      delete: (id: string) => ipcRenderer.invoke('workflow:delete', { id }),
      toggle: (id: string, enabled: boolean) => ipcRenderer.invoke('workflow:toggle', { id, enabled }),
      runManual: (id: string, triggerData?: any) => ipcRenderer.invoke('workflow:runManual', { id, triggerData }),
      getLogs: (id: string, limit?: number) => ipcRenderer.invoke('workflow:getLogs', { id, limit }),
      deleteLogs: (id: string) => ipcRenderer.invoke('workflow:deleteLogs', { id }),
      clone: (id: string, targetZaloId: string) => ipcRenderer.invoke('workflow:clone', { id, targetZaloId }),
      cloneAll: (sourceZaloId: string, targetZaloId: string) => ipcRenderer.invoke('workflow:cloneAll', { sourceZaloId, targetZaloId }),
      getWebhookUrl: (id: string) => ipcRenderer.invoke('workflow:getWebhookUrl', { id }),
      regenerateWebhookToken: (id: string) => ipcRenderer.invoke('workflow:regenerateWebhookToken', { id }),
      startTunnel: () => ipcRenderer.invoke('workflow:startTunnel'),
      stopTunnel: () => ipcRenderer.invoke('workflow:stopTunnel'),
      getTunnelStatus: () => ipcRenderer.invoke('workflow:getTunnelStatus'),
      getPortConfig: () => ipcRenderer.invoke('workflow:getPortConfig'),
      setPortConfig: (key: string, port: number) => ipcRenderer.invoke('workflow:setPortConfig', { key, port }),
  },

  // ─── App-level (badge, open thread) ─────────────────────────────
  app: {
    setBadge: (count: number) => ipcRenderer.send('app:setBadge', count),
    openThread: (params: { zaloId: string; threadId: string; threadType: number }) =>
      ipcRenderer.send('app:openThread', params),
    sendBadgeImage: (params: { dataUrl: string; count: number }) =>
      ipcRenderer.send('app:badgeImage', params),
    flashFrame: (active: boolean) => ipcRenderer.send('app:flashFrame', { active }),
  },

  // ─── Auto-update ─────────────────────────────────────────────────
  update: {
    check:         () => ipcRenderer.send('update:check'),
    download:      () => ipcRenderer.send('update:download'),
    install:       () => ipcRenderer.send('update:install'),
    rendererReady: () => ipcRenderer.send('update:renderer-ready'),
  },

  // ─── Integration Hub ──────────────────────────────────────────────
  integration: {
    list:            () => ipcRenderer.invoke('integration:list'),
    get:             (id: string) => ipcRenderer.invoke('integration:get', { id }),
    save:            (integration: any) => ipcRenderer.invoke('integration:save', { integration }),
    delete:          (id: string) => ipcRenderer.invoke('integration:delete', { id }),
    toggle:          (id: string, enabled: boolean) => ipcRenderer.invoke('integration:toggle', { id, enabled }),
    test:            (id: string) => ipcRenderer.invoke('integration:test', { id }),
    execute:         (id: string, action: string, params?: any) => ipcRenderer.invoke('integration:execute', { id, action, params }),
    executeByType:   (type: string, action: string, params?: any) => ipcRenderer.invoke('integration:executeByType', { type, action, params }),
    getWebhookPort:  () => ipcRenderer.invoke('integration:getWebhookPort'),
  },

  // ─── AI Assistants ────────────────────────────────────────────────
  ai: {
    listAssistants:  () => ipcRenderer.invoke('ai:listAssistants'),
    getAssistant:    (id: string) => ipcRenderer.invoke('ai:getAssistant', { id }),
    getDefault:      () => ipcRenderer.invoke('ai:getDefault'),
    saveAssistant:   (assistant: any) => ipcRenderer.invoke('ai:saveAssistant', { assistant }),
    deleteAssistant: (id: string) => ipcRenderer.invoke('ai:deleteAssistant', { id }),
    testAssistant:   (id: string) => ipcRenderer.invoke('ai:testAssistant', { id }),
    getFiles:        (assistantId: string) => ipcRenderer.invoke('ai:getFiles', { assistantId }),
    uploadFile:      (assistantId: string, filePath: string) => ipcRenderer.invoke('ai:uploadFile', { assistantId, filePath }),
    removeFile:      (fileId: number) => ipcRenderer.invoke('ai:removeFile', { fileId }),
    suggest:         (assistantId: string, chatHistory: any[]) => ipcRenderer.invoke('ai:suggest', { assistantId, chatHistory }),
    chat:            (assistantId: string, messages: any[], structured?: boolean, maxTokens?: number) => ipcRenderer.invoke('ai:chat', { assistantId, messages, structured, maxTokens }),
    getAccountAssistant:  (zaloId: string, role: string) => ipcRenderer.invoke('ai:getAccountAssistant', { zaloId, role }),
    setAccountAssistant:  (zaloId: string, role: string, assistantId: string | null) => ipcRenderer.invoke('ai:setAccountAssistant', { zaloId, role, assistantId }),
    getAccountAssistants: (zaloId: string) => ipcRenderer.invoke('ai:getAccountAssistants', { zaloId }),
    getUsageLogs:  (opts?: any) => ipcRenderer.invoke('ai:getUsageLogs', opts || {}),
    getUsageStats: (opts?: any) => ipcRenderer.invoke('ai:getUsageStats', opts || {}),
    // AI Conversations
    getOrCreateConversation: (params: any) => ipcRenderer.invoke('ai:getOrCreateConversation', params),
    getConversationMessages: (params: any) => ipcRenderer.invoke('ai:getConversationMessages', params),
    addConversationMessage:  (params: any) => ipcRenderer.invoke('ai:addConversationMessage', params),
    getConversations:        (params: any) => ipcRenderer.invoke('ai:getConversations', params),
    deleteConversation:      (params: any) => ipcRenderer.invoke('ai:deleteConversation', params),
  },

  // ─── Tunnel ───────────────────────────────────────────────────────
  tunnel: {
    start:  () => ipcRenderer.invoke('tunnel:start'),
    stop:   () => ipcRenderer.invoke('tunnel:stop'),
    status: () => ipcRenderer.invoke('tunnel:status'),
    getAll: () => ipcRenderer.invoke('tunnel:getAll'),
  },

  // ─── Employee Management ───────────────────────────────────────────
  employee: {
    list:               () => ipcRenderer.invoke('employee:list'),
    getById:            (employeeId: string) => ipcRenderer.invoke('employee:getById', { employeeId }),
    create:             (params: any) => ipcRenderer.invoke('employee:create', params),
    update:             (employeeId: string, updates: any) => ipcRenderer.invoke('employee:update', { employeeId, updates }),
    delete:             (employeeId: string) => ipcRenderer.invoke('employee:delete', { employeeId }),
    setPermissions:     (employeeId: string, permissions: any[]) => ipcRenderer.invoke('employee:setPermissions', { employeeId, permissions }),
    getPermissions:     (employeeId: string) => ipcRenderer.invoke('employee:getPermissions', { employeeId }),
    assignAccounts:     (employeeId: string, zaloIds: string[]) => ipcRenderer.invoke('employee:assignAccounts', { employeeId, zaloIds }),
    getAssignedAccounts:(employeeId: string) => ipcRenderer.invoke('employee:getAssignedAccounts', { employeeId }),
    getStats:           (employeeId: string, sinceTs?: number, untilTs?: number) => ipcRenderer.invoke('employee:getStats', { employeeId, sinceTs, untilTs }),
    getSessions:        (employeeId: string, limit?: number) => ipcRenderer.invoke('employee:getSessions', { employeeId, limit }),
    login:              (username: string, password: string) => ipcRenderer.invoke('employee:login', { username, password }),
    validateToken:      (token: string) => ipcRenderer.invoke('employee:validateToken', { token }),
    setMode:            (mode: string) => ipcRenderer.invoke('employee:setMode', { mode }),
    getMode:            () => ipcRenderer.invoke('employee:getMode'),
    connectToBoss:      (bossUrl: string, token: string) => ipcRenderer.invoke('employee:connectToBoss', { bossUrl, token }),
    disconnectFromBoss: () => ipcRenderer.invoke('employee:disconnectFromBoss'),
    getConnectionStatus:() => ipcRenderer.invoke('employee:getConnectionStatus'),
    proxyAction:        (channel: string, params: any) => ipcRenderer.invoke('employee:proxyAction', { channel, params }),
    // Groups
    listGroups:         () => ipcRenderer.invoke('employee:listGroups'),
    createGroup:        (name: string, color?: string) => ipcRenderer.invoke('employee:createGroup', { name, color }),
    updateGroup:        (groupId: string, updates: any) => ipcRenderer.invoke('employee:updateGroup', { groupId, updates }),
    deleteGroup:        (groupId: string) => ipcRenderer.invoke('employee:deleteGroup', { groupId }),
    // Analytics
    analyticsComparison:     (sinceTs: number, untilTs: number) => ipcRenderer.invoke('employee:analytics:comparison', { sinceTs, untilTs }),
    analyticsMessageTimeline:(sinceTs: number, untilTs: number) => ipcRenderer.invoke('employee:analytics:messageTimeline', { sinceTs, untilTs }),
    analyticsOnlineTimeline: (sinceTs: number, untilTs: number) => ipcRenderer.invoke('employee:analytics:onlineTimeline', { sinceTs, untilTs }),
    analyticsResponseDist:   (sinceTs: number, untilTs: number) => ipcRenderer.invoke('employee:analytics:responseDistribution', { sinceTs, untilTs }),
    analyticsHourlyActivity: (sinceTs: number, untilTs: number) => ipcRenderer.invoke('employee:analytics:hourlyActivity', { sinceTs, untilTs }),
  },

  // ─── Workspace Management ────────────────────────────────────────
  workspace: {
    list:                 () => ipcRenderer.invoke('workspace:list'),
    getActive:            () => ipcRenderer.invoke('workspace:getActive'),
    create:               (params: any) => ipcRenderer.invoke('workspace:create', params),
    update:               (id: string, updates: any) => ipcRenderer.invoke('workspace:update', { id, updates }),
    delete:               (id: string) => ipcRenderer.invoke('workspace:delete', { id }),
    switch:               (id: string) => ipcRenderer.invoke('workspace:switch', { id }),
    isMulti:              () => ipcRenderer.invoke('workspace:isMulti'),
    getDbPath:            (id: string) => ipcRenderer.invoke('workspace:getDbPath', { id }),
    connectRemote:        (id: string, bossUrl: string, token: string) =>
                            ipcRenderer.invoke('workspace:connectRemote', { id, bossUrl, token }),
    disconnectRemote:     (id: string) => ipcRenderer.invoke('workspace:disconnectRemote', { id }),
    getConnectionStatus:  (id: string) => ipcRenderer.invoke('workspace:getConnectionStatus', { id }),
    getAllStatuses:        () => ipcRenderer.invoke('workspace:getAllStatuses'),
    loginRemote:          (bossUrl: string, username: string, password: string) =>
                            ipcRenderer.invoke('workspace:loginRemote', { bossUrl, username, password }),
  },

  // ─── Relay Server (Boss) ──────────────────────────────────────────
  relay: {
    startServer:         (port?: number) => ipcRenderer.invoke('relay:startServer', { port }),
    stopServer:          () => ipcRenderer.invoke('relay:stopServer'),
    getServerStatus:     () => ipcRenderer.invoke('relay:getServerStatus'),
    kickEmployee:        (employeeId: string) => ipcRenderer.invoke('relay:kickEmployee', { employeeId }),
    startTunnel:         () => ipcRenderer.invoke('relay:startTunnel'),
    stopTunnel:          () => ipcRenderer.invoke('relay:stopTunnel'),
    getTunnelStatus:     () => ipcRenderer.invoke('relay:getTunnelStatus'),
  },

  // ─── Facebook ─────────────────────────────────────────────────────
  fb: {
    addAccount:          (params: { cookie: string; proxyId?: number | null }) => ipcRenderer.invoke('fb:addAccount', params),
    addAccountWithCredentials: (params: { username: string; password: string; twoFASecret?: string; proxyId?: number | null }) => ipcRenderer.invoke('fb:addAccountWithCredentials', params),
    removeAccount:       (params: { accountId: string }) => ipcRenderer.invoke('fb:removeAccount', params),
    updateCookie:        (params: { accountId: string; cookie: string }) => ipcRenderer.invoke('fb:updateCookie', params),
    refreshProfile:      (params: { accountId: string }) => ipcRenderer.invoke('fb:refreshProfile', params),
    getAccounts:         () => ipcRenderer.invoke('fb:getAccounts'),
    connect:             (params: { accountId: string }) => ipcRenderer.invoke('fb:connect', params),
    disconnect:          (params: { accountId: string }) => ipcRenderer.invoke('fb:disconnect', params),
    checkHealth:         (params: { accountId: string }) => ipcRenderer.invoke('fb:checkHealth', params),
    sendMessage:         (params: any) => ipcRenderer.invoke('fb:sendMessage', params),
    sendAttachment:      (params: any) => ipcRenderer.invoke('fb:sendAttachment', params),
    sendAttachments:     (params: any) => ipcRenderer.invoke('fb:sendAttachments', params),
    unsendMessage:       (params: any) => ipcRenderer.invoke('fb:unsendMessage', params),
    addReaction:         (params: any) => ipcRenderer.invoke('fb:addReaction', params),
    getThreads:          (params: any) => ipcRenderer.invoke('fb:getThreads', params),
    getMessages:         (params: any) => ipcRenderer.invoke('fb:getMessages', params),
    markAsRead:          (params: any) => ipcRenderer.invoke('fb:markAsRead', params),
    changeThreadName:    (params: any) => ipcRenderer.invoke('fb:changeThreadName', params),
    changeThreadEmoji:   (params: any) => ipcRenderer.invoke('fb:changeThreadEmoji', params),
    changeNickname:      (params: any) => ipcRenderer.invoke('fb:changeNickname', params),
    loginWithCredentials:(params: any) => ipcRenderer.invoke('fb:loginWithCredentials', params),    fetchThreadMessages:   (params: any) => ipcRenderer.invoke('fb:fetchThreadMessages', params),
    refreshContactAvatar:  (params: any) => ipcRenderer.invoke('fb:refreshContactAvatar', params),
    sendTyping:            (params: any) => ipcRenderer.invoke('fb:sendTyping', params),
    blockUser:             (params: any) => ipcRenderer.invoke('fb:blockUser', params),
    unblockUser:           (params: any) => ipcRenderer.invoke('fb:unblockUser', params),
    forwardMessage:        (params: any) => ipcRenderer.invoke('fb:forwardMessage', params),
    editMessage:           (params: any) => ipcRenderer.invoke('fb:editMessage', params),
    createPoll:            (params: any) => ipcRenderer.invoke('fb:createPoll', params),
    getUserInfoFacebookHtml: (params: { accountId: string; userId: string }) => ipcRenderer.invoke('fb:getUserInfoFacebookHtml', params),
    // ─── Scan Data ────────────────────────────────────────────────
    scanGroupMembers:     (params: { accountId: string; groupId: string; cursor?: string | null }) => ipcRenderer.invoke('fb:scanGroupMembers', params),
    scanGroupKeyword:     (params: { accountId: string; keyword: string; cursor?: string | null; filters?: string[]; bsid?: string; tsid?: string }) => ipcRenderer.invoke('fb:scanGroupKeyword', params),
    scanFanpageKeyword:   (params: { accountId: string; keyword: string; cursor?: string | null; filters?: string[]; bsid?: string; tsid?: string }) => ipcRenderer.invoke('fb:scanFanpageKeyword', params),
    scanPostTimeline:     (params: { accountId: string; sourceId: string; sourceType: 'profile' | 'fanpage' | 'group'; cursor?: string | null }) => ipcRenderer.invoke('fb:scanPostTimeline', params),
    scanPostComments:     (params: { accountId: string; postId: string; cursor?: string | null }) => ipcRenderer.invoke('fb:scanPostComments', params),
    scanPostKeyword:      (params: { accountId: string; keyword: string; cursor?: string | null; filters?: string[]; bsid?: string; tsid?: string }) => ipcRenderer.invoke('fb:scanPostKeyword', params),
    // Batch
    scanGroupMembersBatch: (params: { accountId: string; groupIds: string[]; threadCount?: number }) => ipcRenderer.invoke('fb:scanGroupMembersBatch', params),
    scanPostCommentsBatch: (params: { accountId: string; postIds: string[]; threadCount?: number }) => ipcRenderer.invoke('fb:scanPostCommentsBatch', params),
    // Scan history
    saveScanLog:   (params: any) => ipcRenderer.invoke('fb:saveScanLog', params),
    getScanLogs:   (params: { accountId: string; tabId?: string; limit?: number; offset?: number }) => ipcRenderer.invoke('fb:getScanLogs', params),
    // Tab management
    scanSaveTab:       (params: any) => ipcRenderer.invoke('fb:scanSaveTab', params),
    scanGetTabs:       (params: { accountId: string; status?: string; limit?: number; offset?: number }) => ipcRenderer.invoke('fb:scanGetTabs', params),
    scanGetTab:        (params: { id: string }) => ipcRenderer.invoke('fb:scanGetTab', params),
    scanUpdateTabStatus: (params: { id: string; status: string }) => ipcRenderer.invoke('fb:scanUpdateTabStatus', params),
    scanTouchTab:       (params: { id: string }) => ipcRenderer.invoke('fb:scanTouchTab', params),
    scanDeleteTab:     (params: { id: string }) => ipcRenderer.invoke('fb:scanDeleteTab', params),
    scanSaveTabData:   (params: { tabId: string; items: any[]; pageInfo: any }) => ipcRenderer.invoke('fb:scanSaveTabData', params),
    scanGetTabData:    (params: { tabId: string }) => ipcRenderer.invoke('fb:scanGetTabData', params),
    scanSaveRequestLog:(params: any) => ipcRenderer.invoke('fb:scanSaveRequestLog', params),
    scanGetRequestLogs:(params: { tabId: string; limit?: number; offset?: number }) => ipcRenderer.invoke('fb:scanGetRequestLogs', params),
    scanGetStats:      (params: { accountId: string }) => ipcRenderer.invoke('fb:scanGetStats', params),
    scanResetCache:() => ipcRenderer.invoke('fb:scanResetCache'),
  },

  // ─── Telegram Bot ───────────────────────────────────────────────────────
  telegram: {
    validateBot:    (botToken: string) => ipcRenderer.invoke('telegram:validateBot', botToken),
    startBot:       (account: any) => ipcRenderer.invoke('telegram:startBot', account),
    stopBot:        (accountId: string) => ipcRenderer.invoke('telegram:stopBot', accountId),
    isBotPolling:   (params: any) => ipcRenderer.invoke('telegram:isBotPolling', params),
    sendMessage:    (params: any) => ipcRenderer.invoke('telegram:sendMessage', params),
    sendPhoto:      (params: any) => ipcRenderer.invoke('telegram:sendPhoto', params),
    sendVideo:      (params: any) => ipcRenderer.invoke('telegram:sendVideo', params),
    sendDocument:   (params: any) => ipcRenderer.invoke('telegram:sendDocument', params),
    sendAudio:      (params: any) => ipcRenderer.invoke('telegram:sendAudio', params),
    forwardMessage: (params: any) => ipcRenderer.invoke('telegram:forwardMessage', params),
    deleteMessage:  (params: any) => ipcRenderer.invoke('telegram:deleteMessage', params),
    addReaction:    (params: any) => ipcRenderer.invoke('telegram:addReaction', params),
    pinMessage:     (params: any) => ipcRenderer.invoke('telegram:pinMessage', params),
    sendPoll:       (params: any) => ipcRenderer.invoke('telegram:sendPoll', params),
    editMessage:    (params: any) => ipcRenderer.invoke('telegram:editMessage', params),
    getActiveBots:  () => ipcRenderer.invoke('telegram:getActiveBots'),
  },

  // ─── Telegram User (MTProto) ────────────────────────────────────────────
  telegramUser: {
    sendCode:       (phoneNumber: string) => ipcRenderer.invoke('telegramUser:sendCode', phoneNumber),
    signIn:         (params: any) => ipcRenderer.invoke('telegramUser:signIn', params),
    signIn2FA:      (password: string) => ipcRenderer.invoke('telegramUser:signIn2FA', password),
    startListener:  (account: any) => ipcRenderer.invoke('telegramUser:startListener', account),
    stopListener:   (accountId: string) => ipcRenderer.invoke('telegramUser:stopListener', accountId),
    sendMessage:    (params: any) => ipcRenderer.invoke('telegramUser:sendMessage', params),
    editMessage:    (params: any) => ipcRenderer.invoke('telegramUser:editMessage', params),
    deleteMessages: (params: any) => ipcRenderer.invoke('telegramUser:deleteMessages', params),
    forwardMessages:(params: any) => ipcRenderer.invoke('telegramUser:forwardMessages', params),
    pinMessage:     (params: any) => ipcRenderer.invoke('telegramUser:pinMessage', params),
    syncPinnedMessages: (params: any) => ipcRenderer.invoke('telegramUser:syncPinnedMessages', params),
    ensureMessageAvailable: (params: any) => ipcRenderer.invoke('telegramUser:ensureMessageAvailable', params),
    sendFile:       (params: any) => ipcRenderer.invoke('telegramUser:sendFile', params),
    sendTopicFile:  (params: TelegramForumTopicContext & { filePath: string; caption?: string }) => ipcRenderer.invoke('telegramUser:sendTopicFile', params),
    sendTyping:     (params: any) => ipcRenderer.invoke('telegramUser:sendTyping', params),
    sendReaction:   (params: any) => ipcRenderer.invoke('telegramUser:sendReaction', params),
    isConnected:    (accountId: string) => ipcRenderer.invoke('telegramUser:isConnected', accountId),
    getActive:      () => ipcRenderer.invoke('telegramUser:getActive'),
    refreshMessages:(params: { accountId: string }) => ipcRenderer.invoke('telegramUser:refreshMessages', params),
    fetchSelfAvatar:(accountId: string) => ipcRenderer.invoke('telegramUser:fetchSelfAvatar', accountId),
    // Group management
    getGroupInfo:      (params: any) => ipcRenderer.invoke('telegramUser:getGroupInfo', params),
    joinGroup:         (params: any) => ipcRenderer.invoke('telegramUser:joinGroup', params),
    getGroupMembers:   (params: any) => ipcRenderer.invoke('telegramUser:getGroupMembers', params),
    hydrateMessageSenders: (params: any) => ipcRenderer.invoke('telegramUser:hydrateMessageSenders', params),
    setDialogMute:     (params: any) => ipcRenderer.invoke('telegramUser:setDialogMute', params),
    setDialogArchived: (params: any) => ipcRenderer.invoke('telegramUser:setDialogArchived', params),
    setDialogPin:      (params: any) => ipcRenderer.invoke('telegramUser:setDialogPin', params),
    getMessageReactions:(params: any) => ipcRenderer.invoke('telegramUser:getMessageReactions', params),
    addChatUser:       (params: any) => ipcRenderer.invoke('telegramUser:addChatUser', params),
    deleteChatUser:    (params: any) => ipcRenderer.invoke('telegramUser:deleteChatUser', params),
    editChatTitle:     (params: any) => ipcRenderer.invoke('telegramUser:editChatTitle', params),
    editChatPhoto:     (params: any) => ipcRenderer.invoke('telegramUser:editChatPhoto', params),
    editChatAdmin:     (params: any) => ipcRenderer.invoke('telegramUser:editChatAdmin', params),
    leaveChat:         (params: any) => ipcRenderer.invoke('telegramUser:leaveChat', params),
    blockUser:         (params: any) => ipcRenderer.invoke('telegramUser:blockUser', params),
    unblockUser:       (params: any) => ipcRenderer.invoke('telegramUser:unblockUser', params),
    exportChatInvite:  (params: any) => ipcRenderer.invoke('telegramUser:exportChatInvite', params),
    readChatHistory:   (params: any) => ipcRenderer.invoke('telegramUser:readChatHistory', params),
    readForumTopic:    (params: any) => ipcRenderer.invoke('telegramUser:readForumTopic', params),
    getMessages:       (params: any) => ipcRenderer.invoke('telegramUser:getMessages', params),
    repairMessageMedia:(params: { accountId: string; chatId: string; messageId: string }) => ipcRenderer.invoke('telegramUser:repairMessageMedia', params),
    repairEmptyMessages:(params: { accountId: string; chatId: string; messageIds: string[] }) => ipcRenderer.invoke('telegramUser:repairEmptyMessages', params),
    repairMessageQuotes:(params: { accountId: string; chatId: string; items: Array<{ messageId: string; replyToId: string }> }) => ipcRenderer.invoke('telegramUser:repairMessageQuotes', params),
    getFullChat:       (params: any) => ipcRenderer.invoke('telegramUser:getFullChat', params),
    getUserProfile:    (params: any) => ipcRenderer.invoke('telegramUser:getUserProfile', params),
    resolveUsername:   (params: any) => ipcRenderer.invoke('telegramUser:resolveUsername', params),
    searchContacts:    (params: any) => ipcRenderer.invoke('telegramUser:searchContacts', params),
    getPeers:          (params: any) => ipcRenderer.invoke('telegramUser:getPeers', params),
    // Forum / Topics
    isForum:              (params: any) => ipcRenderer.invoke('telegramUser:isForum', params),
    checkForumForNewGroups:(params: any) => ipcRenderer.invoke('telegramUser:checkForumForNewGroups', params),
    getForumTopics:       (params: any) => ipcRenderer.invoke('telegramUser:getForumTopics', params),
    getForumTopicMessages:(params: TelegramForumTopicContext & { limit?: number }) => ipcRenderer.invoke('telegramUser:getForumTopicMessages', params),
    createForumTopic:     (params: any) => ipcRenderer.invoke('telegramUser:createForumTopic', params),
    editForumTopic:       (params: TelegramForumTopicContext & { title?: string; iconEmojiId?: string; closed?: boolean; pinned?: boolean }) => ipcRenderer.invoke('telegramUser:editForumTopic', params),
    sendTopicMessage:     (params: TelegramForumTopicContext & { text: string }) => ipcRenderer.invoke('telegramUser:sendTopicMessage', params),
    // Sticker / GIF
    getStickerSets:       (params: any) => ipcRenderer.invoke('telegramUser:getStickerSets', params),
    getStickerSetStickers:(params: any) => ipcRenderer.invoke('telegramUser:getStickerSetStickers', params),
    getRecentStickers:    (params: any) => ipcRenderer.invoke('telegramUser:getRecentStickers', params),
    getGifs:              (params: any) => ipcRenderer.invoke('telegramUser:getGifs', params),
    searchGifs:           (params: any) => ipcRenderer.invoke('telegramUser:searchGifs', params),
    sendSticker:          (params: any) => ipcRenderer.invoke('telegramUser:sendSticker', params),
    sendGif:              (params: any) => ipcRenderer.invoke('telegramUser:sendGif', params),
    downloadSticker:      (params: any) => ipcRenderer.invoke('telegramUser:downloadSticker', params),
  },

  // ─── ERP ─────────────────────────────────────────────────────────
  erp: {
    // Projects
    projectList:        (params?: any) => ipcRenderer.invoke('erp:project:list', params),
    projectCreate:      (params: any) => ipcRenderer.invoke('erp:project:create', params),
    projectUpdate:      (params: any) => ipcRenderer.invoke('erp:project:update', params),
    projectDelete:      (params: any) => ipcRenderer.invoke('erp:project:delete', params),
    // Tasks
    taskList:           (params?: any) => ipcRenderer.invoke('erp:task:list', params),
    taskGet:            (params: any) => ipcRenderer.invoke('erp:task:get', params),
    taskCreate:         (params: any) => ipcRenderer.invoke('erp:task:create', params),
    taskUpdate:         (params: any) => ipcRenderer.invoke('erp:task:update', params),
    taskUpdateStatus:   (params: any) => ipcRenderer.invoke('erp:task:updateStatus', params),
    taskAssign:         (params: any) => ipcRenderer.invoke('erp:task:assign', params),
    taskDelete:         (params: any) => ipcRenderer.invoke('erp:task:delete', params),
    taskAddChecklist:   (params: any) => ipcRenderer.invoke('erp:task:addChecklist', params),
    taskToggleChecklist:(params: any) => ipcRenderer.invoke('erp:task:toggleChecklist', params),
    taskAddComment:     (params: any) => ipcRenderer.invoke('erp:task:addComment', params),
    taskEditComment:    (params: any) => ipcRenderer.invoke('erp:task:editComment', params),
    taskDeleteComment:  (params: any) => ipcRenderer.invoke('erp:task:deleteComment', params),
    taskListMyInbox:    (params: any) => ipcRenderer.invoke('erp:task:listMyInbox', params),
    // Calendar
    calendarListEvents: (params: any) => ipcRenderer.invoke('erp:calendar:listEvents', params),
    calendarCreate:     (params: any) => ipcRenderer.invoke('erp:calendar:createEvent', params),
    calendarUpdate:     (params: any) => ipcRenderer.invoke('erp:calendar:updateEvent', params),
    calendarDelete:     (params: any) => ipcRenderer.invoke('erp:calendar:deleteEvent', params),
    calendarCheckConflict:(params: any) => ipcRenderer.invoke('erp:calendar:checkConflict', params),
    // Notes
    noteListFolders:    (params: any) => ipcRenderer.invoke('erp:note:listFolders', params),
    noteCreateFolder:   (params: any) => ipcRenderer.invoke('erp:note:createFolder', params),
    noteRenameFolder:   (params: any) => ipcRenderer.invoke('erp:note:renameFolder', params),
    noteDeleteFolder:   (params: any) => ipcRenderer.invoke('erp:note:deleteFolder', params),
    noteList:           (params?: any) => ipcRenderer.invoke('erp:note:list', params),
    noteGet:            (params: any) => ipcRenderer.invoke('erp:note:get', params),
    noteCreate:         (params: any) => ipcRenderer.invoke('erp:note:create', params),
    noteUpdate:         (params: any) => ipcRenderer.invoke('erp:note:update', params),
    noteDelete:         (params: any) => ipcRenderer.invoke('erp:note:delete', params),
    notePin:            (params: any) => ipcRenderer.invoke('erp:note:pin', params),
    noteListTags:       () => ipcRenderer.invoke('erp:note:listTags'),
    noteCreateTag:      (params: any) => ipcRenderer.invoke('erp:note:createTag', params),
    noteAddTag:         (params: any) => ipcRenderer.invoke('erp:note:addTag', params),
    noteRemoveTag:      (params: any) => ipcRenderer.invoke('erp:note:removeTag', params),
    noteVersions:       (params: any) => ipcRenderer.invoke('erp:note:versions', params),
    noteRestoreVersion: (params: any) => ipcRenderer.invoke('erp:note:restoreVersion', params),
    noteShare:          (params: any) => ipcRenderer.invoke('erp:note:share', params),
    noteListShares:     (params: any) => ipcRenderer.invoke('erp:note:listShares', params),
    // Task watchers/dependencies (Phase 2)
    taskAddWatcher:     (params: any) => ipcRenderer.invoke('erp:task:addWatcher', params),
    taskRemoveWatcher:  (params: any) => ipcRenderer.invoke('erp:task:removeWatcher', params),
    taskAddDependency:  (params: any) => ipcRenderer.invoke('erp:task:addDependency', params),
    taskRemoveDependency:(params: any) => ipcRenderer.invoke('erp:task:removeDependency', params),
    // Calendar respond (Phase 2)
    calendarRespond:    (params: any) => ipcRenderer.invoke('erp:calendar:respond', params),
    // HRM (Phase 2)
    departmentList:     () => ipcRenderer.invoke('erp:department:list'),
    departmentCreate:   (params: any) => ipcRenderer.invoke('erp:department:create', params),
    departmentUpdate:   (params: any) => ipcRenderer.invoke('erp:department:update', params),
    departmentDelete:   (params: any) => ipcRenderer.invoke('erp:department:delete', params),
    positionList:       () => ipcRenderer.invoke('erp:position:list'),
    positionCreate:     (params: any) => ipcRenderer.invoke('erp:position:create', params),
    positionUpdate:     (params: any) => ipcRenderer.invoke('erp:position:update', params),
    positionDelete:     (params: any) => ipcRenderer.invoke('erp:position:delete', params),
    employeeGetProfile: (params: any) => ipcRenderer.invoke('erp:employee:getProfile', params),
    employeeUpdateProfile:(params: any) => ipcRenderer.invoke('erp:employee:updateProfile', params),
    employeeListByDepartment:(params: any) => ipcRenderer.invoke('erp:employee:listByDepartment', params),
    employeeDeleteProfile:(params: any) => ipcRenderer.invoke('erp:employee:deleteProfile', params),
    attendanceCheckIn:  (params: any) => ipcRenderer.invoke('erp:attendance:checkIn', params),
    attendanceCheckOut: (params: any) => ipcRenderer.invoke('erp:attendance:checkOut', params),
    attendanceToday:    () => ipcRenderer.invoke('erp:attendance:today'),
    attendanceList:     (params: any) => ipcRenderer.invoke('erp:attendance:list', params),
    leaveCreate:        (params: any) => ipcRenderer.invoke('erp:leave:create', params),
    leaveListMy:        () => ipcRenderer.invoke('erp:leave:listMy'),
    leaveListPending:   () => ipcRenderer.invoke('erp:leave:listPending'),
    leaveDecide:        (params: any) => ipcRenderer.invoke('erp:leave:decide', params),
    leaveCancel:        (params: any) => ipcRenderer.invoke('erp:leave:cancel', params),
    licenseSeatStatus:  () => ipcRenderer.invoke('erp:license:seatStatus'),
    // Notifications
    notifyListInbox:    (params: any) => ipcRenderer.invoke('erp:notify:listInbox', params),
    notifyMarkRead:     (params: any) => ipcRenderer.invoke('erp:notify:markRead', params),
    notifyMarkAllRead:  (params: any) => ipcRenderer.invoke('erp:notify:markAllRead', params),
    notifyUnreadCount:  (params: any) => ipcRenderer.invoke('erp:notify:unreadCount', params),
    notifyDelete:       (params: any) => ipcRenderer.invoke('erp:notify:delete', params),
    notifyDeleteAll:    (params: any) => ipcRenderer.invoke('erp:notify:deleteAll', params),
  },
  lockScreen: {
    status:           () => ipcRenderer.invoke('lockScreen:status'),
    setup:            (params: { password: string }) => ipcRenderer.invoke('lockScreen:setup', params),
    verify:           (params: { password: string }) => ipcRenderer.invoke('lockScreen:verify', params),
    verifyRecovery:   (params: { recoveryKey: string }) => ipcRenderer.invoke('lockScreen:verifyRecovery', params),
    changePassword:   (params: { oldPassword: string; newPassword: string }) => ipcRenderer.invoke('lockScreen:changePassword', params),
    resetPassword:    (params: { recoveryKey: string; newPassword: string }) => ipcRenderer.invoke('lockScreen:resetPassword', params),
    disable:          (params: { password: string }) => ipcRenderer.invoke('lockScreen:disable', params),
    getRecoveryKey:   (params: { password: string }) => ipcRenderer.invoke('lockScreen:getRecoveryKey', params),
    setBiometric:     (params: { enabled: boolean }) => ipcRenderer.invoke('lockScreen:setBiometric', params),
    biometricUnlock:  () => ipcRenderer.invoke('lockScreen:biometricUnlock'),
  },

  // ─── Media Library ───────────────────────────────────────────────
  library: {
    getItems:    (params: any) => ipcRenderer.invoke('library:getItems', params),
    upload:      (params: any) => ipcRenderer.invoke('library:upload', params),
    deleteItem:  (uuid: string) => ipcRenderer.invoke('library:deleteItem', uuid),
    getFolders:  (params: { zaloId: string; type?: string }) => ipcRenderer.invoke('library:getFolders', params),
    createFolder:(params: any) => ipcRenderer.invoke('library:createFolder', params),
    updateItem:  (uuid: string, params: any) => ipcRenderer.invoke('library:updateItem', { uuid, ...params }),
    renameFolder:(id: number, name: string) => ipcRenderer.invoke('library:renameFolder', { id, name }),
    deleteFolder:(id: number) => ipcRenderer.invoke('library:deleteFolder', id),
  },
  on: (channel: string, callback: (...args: any[]) => void) => {
    const validChannels = [
      'event:message',
      'event:connected',
      'event:disconnected',
      'event:reaction',
      'event:telegramReaction',
      'event:messageEdited',
      'event:messagesDeleted',
      'event:userPresence',
      'event:telegramEntityHydrated',
      'event:forumTopicsChanged',
      'event:groupMemberAvatar',
      'event:friendRequest',
      'event:friendAccepted',
      'event:groupEvent',
      'event:groupInfoUpdate',
      'event:undo',
      'event:delete',
      'event:reminder',
      'event:localPath',
      'event:listenerDead',
      'event:pinsUpdated',
      'event:typing',
      'event:seen',
      'qr:update',
      'update:available',
      'update:progress',
      'update:downloaded',
      'update:error',
      'app:openThread',
      'app:windowFocus',
      'app:drawBadge',
      'crm:queueUpdate',
      'crm:queueStatus',
      'crm:campaignDone',
      'workflow:executed',
      'db:copyProgress',
      'integration:webhook',
      'integration:payment',
      'tunnel:changed',
      'tunnel:onChange',
      'workflow:webhookRegistered',
      'relay:employeeListUpdate',
      'relay:messageSentByEmployee',
      'relay:tunnelStatusUpdate',
      'workspace:switched',
      'workspace:connectionStatus',
      'workspace:initialState',
      'workspace:accountAccessUpdate',
      'workspace:permissionUpdate',
      'workspace:syncComplete',
      'employee:modeChanged',
      // ─── Facebook events ─────────────────────────────────────────────
      'fb:onMessage',
      'fb:onReaction',
      'fb:onEdit',
      'fb:onUnsend',
      'fb:onDisconnect',
      'fb:onReconnect',
      'fb:onConnectionStatus',
      // ─── ERP events ──────────────────────────────────────────────────
      'erp:event:taskCreated',
      'erp:event:taskUpdated',
      'erp:event:taskDeleted',
      'erp:event:commentAdded',
      'erp:event:projectCreated',
      'erp:event:projectUpdated',
      'erp:event:projectDeleted',
      'erp:event:calendarEventCreated',
      'erp:event:calendarEventUpdated',
      'erp:event:calendarEventDeleted',
      'erp:event:noteCreated',
      'erp:event:noteUpdated',
      'erp:event:noteDeleted',
      'erp:event:notification',
      'erp:event:reminder',
      'erp:event:leaveCreated',
      'erp:event:leaveDecided',
      'erp:event:attendanceUpdated',
      // ─── CRM / Settings real-time sync ──────────────────────────────
      'db:localLabelChanged',
      'db:localLabelThreadChanged',
      'db:pinnedMessageChanged',
      'db:localQuickMessageChanged',
      'crm:campaignChanged',
      'crm:noteChanged',
      'db:pinnedConversationChanged',
      'db:contactFlagsChanged',
      'db:contactAliasChanged',
      'db:unreadChanged',
      'db:conversationDeleted',
      'db:contactProfileUpdated',
      'crm:tagChanged',
      'event:friendRequestSent',
      'event:friendRequestRemoved',
      'event:pollVote',
      'erp:event:noteShared',
      'erp:event:departmentUpdated',
      'erp:event:employeeProfileUpdated',
      'erp:event:employeeProfileDeleted',
      // ─── Library events ──────────────────────────────────────────
      'library:itemAdded',
      'library:itemUpdated',
      'library:itemDeleted',
    ];
    if (validChannels.includes(channel)) {
      const subscription = (_event: any, ...args: any[]) => callback(...args);
      ipcRenderer.on(channel, subscription);
      return () => ipcRenderer.removeListener(channel, subscription);
    }
    return () => {};
  },

  removeAllListeners: (channel: string) => {
    ipcRenderer.removeAllListeners(channel);
  },

  // ─── Proxy ───────────────────────────────────────────────────────────────
  proxy: {
    list:          ()                              => ipcRenderer.invoke('proxy:list'),
    save:          (proxy: any)                    => ipcRenderer.invoke('proxy:save', { proxy }),
    update:        (id: number, proxy: any)        => ipcRenderer.invoke('proxy:update', { id, proxy }),
    delete:        (id: number)                    => ipcRenderer.invoke('proxy:delete', { id }),
    setAccount:    (zaloId: string, proxyId: number | null) => ipcRenderer.invoke('proxy:setAccount', { zaloId, proxyId }),
    getForAccount: (zaloId: string)                => ipcRenderer.invoke('proxy:getForAccount', { zaloId }),
    test:          (proxy: any)                    => ipcRenderer.invoke('proxy:test', { proxy }),
  },
});
