import { socketInvoke, socketSend, socketOn, socketOff, isElectron } from './socketClient';
import type { TelegramForumTopicContext } from '../../models/telegram';

// Expose typed API to renderer ONLY if not in Electron natively
if (!isElectron) {
  (window as any).electronAPI = {
  // ─── Platform info ──────────────────────────────────────────────
  platform: typeof process !== 'undefined' ? process.platform : 'win32',  // 'darwin' | 'win32' | 'linux'

  // ─── Window Controls ─────────────────────────────────────────────
  window: {
    minimize: () => socketSend('window:minimize'),
    maximize: () => socketSend('window:maximize'),
    close: () => socketSend('window:close'),
    quit: () => socketSend('window:quit'),
    isMaximized: () => socketInvoke('window:isMaximized').catch(() => false),
  },

  // ─── Shell ───────────────────────────────────────────────────────
  shell: {
    openExternal: (url: string) => socketSend('shell:openExternal', url),
    openPath: (filePath: string) => socketInvoke('shell:openPath', filePath),
    openInApp: (url: string) => socketInvoke('shell:openInApp', url),
  },

  // ─── Util ───────────────────────────────────────────────────────
  util: {
    fetchUrl: (args: { url: string }) => socketInvoke('util:fetchUrl', args),
  },

  // ─── Login / Account ─────────────────────────────────────────────
  login: {
    loginQR: (tempId: string, proxyId?: number | null) => socketInvoke('login:qr', { tempId, proxyId }),
    loginQRAbort: (tempId: string) => socketInvoke('login:qr:abort', { tempId }),
    loginCookies: (imei: string, cookies: string, userAgent: string) =>
      socketInvoke('login:cookies', { imei, cookies, userAgent }),
    loginAuth: (authJson: string, proxyId?: number | null) => socketInvoke('login:auth', { authJson, proxyId }),
    openZaloWebviewLogin: (proxyId?: number | null) => socketInvoke('login:openZaloWebview', proxyId),
    connectAccount: (auth: any) => socketInvoke('login:connect', { auth }),
    disconnectAccount: (zaloId: string) => socketInvoke('login:disconnect', { zaloId }),
    disconnectAll: () => socketInvoke('login:disconnectAll'),
    getAccounts: () => socketInvoke('login:getAccounts'),
    removeAccount: (zaloId: string, deleteData?: boolean) => socketInvoke('login:removeAccount', { zaloId, deleteData }),
    getMediaAutoDelete: (zaloId: string) => socketInvoke('login:getMediaAutoDelete', { zaloId }),
    setMediaAutoDelete: (zaloId: string, enabled: boolean, days: number) => socketInvoke('login:setMediaAutoDelete', { zaloId, enabled, days }),
    runAllMediaCleanup: () => socketInvoke('login:runAllMediaCleanup'),
    checkHealth: (zaloIds: string | string[]) => socketInvoke('login:checkHealth', { zaloIds }),
    checkAndRefreshAvatar: (zaloId: string) => socketInvoke('login:checkAndRefreshAvatar', { zaloId }),
    requestOldMessages: (zaloId: string) => socketInvoke('login:requestOldMessages', { zaloId }),
  },

  // ─── Zalo API ────────────────────────────────────────────────────
  zalo: {
    sendMessage: (params: any) => socketInvoke('zalo:sendMessage', params),
    sendImage: (params: any) => socketInvoke('zalo:sendImage', params),
    sendImages: (params: any) => socketInvoke('zalo:sendImages', params),
    sendFile: (params: any) => socketInvoke('zalo:sendFile', params),
    sendSticker: (params: any) => socketInvoke('zalo:sendSticker', params),
    sendVoice: (params: any) => socketInvoke('zalo:sendVoice', params),
    sendVideo: (params: any) => socketInvoke('zalo:sendVideo', params),
    sendLink: (params: any) => socketInvoke('zalo:sendLink', params),
    sendCard: (params: any) => socketInvoke('zalo:sendCard', params),
    undoMessage: (params: any) => socketInvoke('zalo:undoMessage', params),
    deleteMessage: (params: any) => socketInvoke('zalo:deleteMessage', params),
    deleteChat: (params: any) => socketInvoke('zalo:deleteChat', params),
    addReaction: (params: any) => socketInvoke('zalo:addReaction', params),
    forwardMessage: (params: any) => socketInvoke('zalo:forwardMessage', params),
    getFriends: (auth: any) => socketInvoke('zalo:getFriends', { auth }),
    getGroups: (auth: any) => socketInvoke('zalo:getGroups', { auth }),
    getUserInfo: (params: any) => socketInvoke('zalo:getUserInfo', params),
    getContext: (params: any) => socketInvoke('zalo:getContext', params),
    findUser: (params: any) => socketInvoke('zalo:findUser', params),
    sendFriendRequest: (params: any) => socketInvoke('zalo:sendFriendRequest', params),
    acceptFriendRequest: (params: any) => socketInvoke('zalo:acceptFriendRequest', params),
    rejectFriendRequest: (params: any) => socketInvoke('zalo:rejectFriendRequest', params),
    undoFriendRequest: (params: any) => socketInvoke('zalo:undoFriendRequest', params),
    removeFriend: (params: any) => socketInvoke('zalo:removeFriend', params),
    getSentFriendRequests: (auth: any) => socketInvoke('zalo:getSentFriendRequests', { auth }),
    getFriendRequestStatus: (params: any) => socketInvoke('zalo:getFriendRequestStatus', params),
    getFriendRecommendations: (auth: any) => socketInvoke('zalo:getFriendRecommendations', { auth }),
    getAliasList: (params: any) => socketInvoke('zalo:getAliasList', params),
    blockUser: (params: any) => socketInvoke('zalo:blockUser', params),
    unblockUser: (params: any) => socketInvoke('zalo:unblockUser', params),
    getRelatedFriendGroup: (params: any) => socketInvoke('zalo:getRelatedFriendGroup', params),
    createGroup: (params: any) => socketInvoke('zalo:createGroup', params),
    getGroupInfo: (params: any) => socketInvoke('zalo:getGroupInfo', params),
    addUserToGroup: (params: any) => socketInvoke('zalo:addUserToGroup', params),
    removeUserFromGroup: (params: any) => socketInvoke('zalo:removeUserFromGroup', params),
    leaveGroup: (params: any) => socketInvoke('zalo:leaveGroup', params),
    changeGroupName: (params: any) => socketInvoke('zalo:changeGroupName', params),
    changeGroupAvatar: (params: any) => socketInvoke('zalo:changeGroupAvatar', params),
    changeGroupOwner: (params: any) => socketInvoke('zalo:changeGroupOwner', params),
    disperseGroup: (params: any) => socketInvoke('zalo:disperseGroup', params),
    addGroupDeputy: (params: any) => socketInvoke('zalo:addGroupDeputy', params),
    removeGroupDeputy: (params: any) => socketInvoke('zalo:removeGroupDeputy', params),
    getGroupMembersInfo: (params: any) => socketInvoke('zalo:getGroupMembersInfo', params),
    addGroupBlockedMember: (params: any) => socketInvoke('zalo:addGroupBlockedMember', params),
    removeGroupBlockedMember: (params: any) => socketInvoke('zalo:removeGroupBlockedMember', params),
    getGroupBlockedMember: (params: any) => socketInvoke('zalo:getGroupBlockedMember', params),
    inviteUserToGroups: (params: any) => socketInvoke('zalo:inviteUserToGroups', params),
    updateGroupSettings: (params: any) => socketInvoke('zalo:updateGroupSettings', params),
    getGroupLinkDetail: (params: any) => socketInvoke('zalo:getGroupLinkDetail', params),
    getGroupLinkInfo: (params: any) => socketInvoke('zalo:getGroupLinkInfo', params),
    joinGroupLink: (params: any) => socketInvoke('zalo:joinGroupLink', params),
    enableGroupLink: (params: any) => socketInvoke('zalo:enableGroupLink', params),
    disableGroupLink: (params: any) => socketInvoke('zalo:disableGroupLink', params),
    getPendingGroupMembers: (params: any) => socketInvoke('zalo:getPendingGroupMembers', params),
    reviewPendingMemberRequest: (params: any) => socketInvoke('zalo:reviewPendingMemberRequest', params),
    getMessageHistory: (params: any) => socketInvoke('zalo:getMessageHistory', params),
    getGroupChatHistory: (params: any) => socketInvoke('zalo:getGroupChatHistory', params),
    getPinConversations: (auth: any) => socketInvoke('zalo:getPinConversations', { auth }),
    setPinConversation: (params: any) => socketInvoke('zalo:setPinConversation', params),
    setMute: (params: any) => socketInvoke('zalo:setMute', params),
    keepAlive: (auth: any) => socketInvoke('zalo:keepAlive', { auth }),
    getLabels: (params: any) => socketInvoke('zalo:getLabels', params),
    updateLabels: (params: any) => socketInvoke('zalo:updateLabels', params),
    changeFriendAlias: (params: any) => socketInvoke('zalo:changeFriendAlias', params),
    getStickers: (params: any) => socketInvoke('zalo:getStickers', params),
    getStickersDetail: (params: any) => socketInvoke('zalo:getStickersDetail', params),
    getStickerCategoryDetail: (params: any) => socketInvoke('zalo:getStickerCategoryDetail', params),
    addUnreadMark: (params: any) => socketInvoke('zalo:addUnreadMark', params),
    removeUnreadMark: (params: any) => socketInvoke('zalo:removeUnreadMark', params),
    createPoll: (params: any) => socketInvoke('zalo:createPoll', params),
    getPollDetail: (params: any) => socketInvoke('zalo:getPollDetail', params),
    lockPoll: (params: any) => socketInvoke('zalo:lockPoll', params),
    doVotePoll: (params: any) => socketInvoke('zalo:doVotePoll', params),
    addPollOption: (params: any) => socketInvoke('zalo:addPollOption', params),
    uploadVideoThumb: (params: any) => socketInvoke('zalo:uploadVideoThumb', params),
    uploadVideoFile: (params: any) => socketInvoke('zalo:uploadVideoFile', params),
    uploadVoiceFile: (params: any) => socketInvoke('zalo:uploadVoiceFile', params),
    getQuickMessageList: (params: any) => socketInvoke('zalo:getQuickMessageList', params),
    addQuickMessage: (params: any) => socketInvoke('zalo:addQuickMessage', params),
    updateQuickMessage: (params: any) => socketInvoke('zalo:updateQuickMessage', params),
    removeQuickMessage: (params: any) => socketInvoke('zalo:removeQuickMessage', params),
    createNote: (params: any) => socketInvoke('zalo:createNote', params),
    editNote: (params: any) => socketInvoke('zalo:editNote', params),
    createReminder: (params: any) => socketInvoke('zalo:createReminder', params),
    editReminder: (params: any) => socketInvoke('zalo:editReminder', params),
    removeReminder: (params: any) => socketInvoke('zalo:removeReminder', params),
    getListReminder: (params: any) => socketInvoke('zalo:getListReminder', params),
    getReminder: (params: any) => socketInvoke('zalo:getReminder', params),
    sendSeenEvent: (params: any) => socketInvoke('zalo:sendSeenEvent', params),
    sendBankCard: (params: any) => socketInvoke('zalo:sendBankCard', params),
  },

    db: {
    getMessages: (params: any) => socketInvoke('db:getMessages', params),
    getMessagesAround: (params: any) => socketInvoke('db:getMessagesAround', params),
    getContacts: (zaloId: string) => socketInvoke('db:getContacts', { zaloId }),
    getContactsFiltered: (params: any) => socketInvoke('db:getContactsFiltered', params),
    saveAccount: (account: any) => socketInvoke('db:saveAccount', account),
    searchContactByPhone: (params: { zaloId: string; phone: string }) => socketInvoke('db:searchContactByPhone', params),
    searchMessages: (params: any) => socketInvoke('db:searchMessages', params),
    getMediaMessages: (params: any) => socketInvoke('db:getMediaMessages', params),
    getFileMessages: (params: any) => socketInvoke('db:getFileMessages', params),
    getUnreadCount: (zaloId: string) => socketInvoke('db:getUnreadCount', { zaloId }),
    markAsRead: (params: any) => socketInvoke('db:markAsRead', params),
    markMessageRecalled: (params: any) => socketInvoke('db:markMessageRecalled', params),
    deleteMessages: (params: any) => socketInvoke('db:deleteMessages', params),
    updateContactProfile: (params: any) => socketInvoke('db:updateContactProfile', params),
    updateAccountPhone: (params: any) => socketInvoke('db:updateAccountPhone', params),
    updateReaction: (params: any) => socketInvoke('db:updateReaction', params),
    updateLocalPaths: (params: any) => socketInvoke('db:updateLocalPaths', params),
    getMessageById: (params: any) => socketInvoke('db:getMessageById', params),
    getMessagesByIds: (params: any) => socketInvoke('db:getMessagesByIds', params),
    getStoragePath: () => socketInvoke('db:getStoragePath'),
    setStoragePath: (params: any) => socketInvoke('db:setStoragePath', params),
    selectStorageFolder: () => socketInvoke('db:selectStorageFolder'),
    getFriends: (params: any) => socketInvoke('db:getFriends', params),
    saveFriends: (params: any) => socketInvoke('db:saveFriends', params),
    isFriend: (params: any) => socketInvoke('db:isFriend', params),
    getFriendRequests: (params: any) => socketInvoke('db:getFriendRequests', params),
    saveFriendRequests: (params: any) => socketInvoke('db:saveFriendRequests', params),
    upsertFriendRequest: (params: any) => socketInvoke('db:upsertFriendRequest', params),
    removeFriendRequest: (params: any) => socketInvoke('db:removeFriendRequest', params),
    addFriend: (params: any) => socketInvoke('db:addFriend', params),
    removeFriend: (params: any) => socketInvoke('db:removeFriend', params),
    deleteConversation: (params: any) => socketInvoke('db:deleteConversation', params),
    getLinks: (params: any) => socketInvoke('db:getLinks', params),
    saveLink: (params: any) => socketInvoke('db:saveLink', params),
    getGroupMembers: (params: any) => socketInvoke('db:getGroupMembers', params),
    getAllGroupMembers: (params: any) => socketInvoke('db:getAllGroupMembers', params),
    saveGroupMembers: (params: any) => socketInvoke('db:saveGroupMembers', params),
    upsertGroupMember: (params: any) => socketInvoke('db:upsertGroupMember', params),
    removeGroupMember: (params: any) => socketInvoke('db:removeGroupMember', params),
    saveStickers: (params: any) => socketInvoke('db:saveStickers', params),
    getStickerById: (params: any) => socketInvoke('db:getStickerById', params),
    getRecentStickers: (params?: any) => socketInvoke('db:getRecentStickers', params || {}),
    addRecentSticker: (params: any) => socketInvoke('db:addRecentSticker', params),
    markStickerUnsupported: (params: any) => socketInvoke('db:markStickerUnsupported', params),
    saveStickerPacks: (params: any) => socketInvoke('db:saveStickerPacks', params),
    getStickerPacks: (params?: any) => socketInvoke('db:getStickerPacks', params || {}),
    getStickersByPackId: (params: any) => socketInvoke('db:getStickersByPackId', params),
    saveKeywordStickers: (params: any) => socketInvoke('db:saveKeywordStickers', params),
    getKeywordStickers: (params: any) => socketInvoke('db:getKeywordStickers', params),
    getStickersByIds: (params: any) => socketInvoke('db:getStickersByIds', params),
    getAllCachedPackSummaries: (params?: any) => socketInvoke('db:getAllCachedPackSummaries', params || {}),
    getPinnedMessages: (params: any) => socketInvoke('db:getPinnedMessages', params),
    getMessagesByType: (params: any) => socketInvoke('db:getMessagesByType', params),
    pinMessage: (params: any) => socketInvoke('db:pinMessage', params),
    unpinMessage: (params: any) => socketInvoke('db:unpinMessage', params),
    bringPinnedToTop: (params: any) => socketInvoke('db:bringPinnedToTop', params),
    getLocalQuickMessages: (params: any) => socketInvoke('db:getLocalQuickMessages', params),
    upsertLocalQuickMessage: (params: any) => socketInvoke('db:upsertLocalQuickMessage', params),
    deleteLocalQuickMessage: (params: any) => socketInvoke('db:deleteLocalQuickMessage', params),
    bulkReplaceLocalQuickMessages: (params: any) => socketInvoke('db:bulkReplaceLocalQuickMessages', params),
    getAllLocalQuickMessages: () => socketInvoke('db:getAllLocalQuickMessages'),
    cloneLocalQuickMessages: (params: any) => socketInvoke('db:cloneLocalQuickMessages', params),
    setLocalQMActive: (params: any) => socketInvoke('db:setLocalQMActive', params),
    setLocalQMOrder: (params: any) => socketInvoke('db:setLocalQMOrder', params),

    // Local Labels
    getLocalLabels: (params: any) => socketInvoke('db:getLocalLabels', params),
    upsertLocalLabel: (params: any) => socketInvoke('db:upsertLocalLabel', params),
    deleteLocalLabel: (params: any) => socketInvoke('db:deleteLocalLabel', params),
    cloneLocalLabels: (params: any) => socketInvoke('db:cloneLocalLabels', params),
    getLocalLabelThreads: (params: any) => socketInvoke('db:getLocalLabelThreads', params),
    assignLocalLabelToThread: (params: any) => socketInvoke('db:assignLocalLabelToThread', params),
    bulkAssignLocalLabelToThread: (params: any) => socketInvoke('db:bulkAssignLocalLabelToThread', params),
    removeLocalLabelFromThread: (params: any) => socketInvoke('db:removeLocalLabelFromThread', params),
    getThreadLocalLabels: (params: any) => socketInvoke('db:getThreadLocalLabels', params),
    setLocalLabelActive: (params: any) => socketInvoke('db:setLocalLabelActive', params),
    setLocalLabelOrder: (params: any) => socketInvoke('db:setLocalLabelOrder', params),
    getNotifSettings: (zaloId: string) => socketInvoke('db:getNotifSettings', { zaloId }),
    setNotifSettings: (params: any) => socketInvoke('db:setNotifSettings', params),

    setContactFlags: (params: any) => socketInvoke('db:setContactFlags', params),
    getContactsWithFlags: (params: any) => socketInvoke('db:getContactsWithFlags', params),
    setContactAlias: (params: any) => socketInvoke('db:setContactAlias', params),

    // Message Drafts
    upsertDraft: (params: any) => socketInvoke('db:upsertDraft', params),
    deleteDraft: (params: any) => socketInvoke('db:deleteDraft', params),
    getDraft: (params: any) => socketInvoke('db:getDraft', params),
    getDrafts: (params: any) => socketInvoke('db:getDrafts', params),
    deleteOldDrafts: (params?: any) => socketInvoke('db:deleteOldDrafts', params || {}),

    // Bank Cards
    getBankCards: (params: any) => socketInvoke('db:getBankCards', params),
    upsertBankCard: (params: any) => socketInvoke('db:upsertBankCard', params),
    deleteBankCard: (params: any) => socketInvoke('db:deleteBankCard', params),

    // Local Pinned Conversations
    getLocalPinnedConversations: (params: any) => socketInvoke('db:getLocalPinnedConversations', params),
    setLocalPinnedConversation: (params: any) => socketInvoke('db:setLocalPinnedConversation', params),
  },

  // ─── CRM ─────────────────────────────────────────────────────────
  crm: {
    getNotes: (params: any) => socketInvoke('crm:getNotes', params),
    saveNote: (params: any) => socketInvoke('crm:saveNote', params),
    deleteNote: (params: any) => socketInvoke('crm:deleteNote', params),
    getContacts: (params: any) => socketInvoke('crm:getContacts', params),
    getContactStats: (params: any) => socketInvoke('crm:getContactStats', params),
    getCampaigns: (params: any) => socketInvoke('crm:getCampaigns', params),
    saveCampaign: (params: any) => socketInvoke('crm:saveCampaign', params),
    deleteCampaign: (params: any) => socketInvoke('crm:deleteCampaign', params),
    cloneCampaign: (params: any) => socketInvoke('crm:cloneCampaign', params),
    updateCampaignStatus: (params: any) => socketInvoke('crm:updateCampaignStatus', params),
    addCampaignContacts: (params: any) => socketInvoke('crm:addCampaignContacts', params),
    getCampaignContacts: (params: any) => socketInvoke('crm:getCampaignContacts', params),
    getSendLog: (params: any) => socketInvoke('crm:getSendLog', params),
    getQueueStatus: (params: any) => socketInvoke('crm:getQueueStatus', params),
    getCampaignStats: (params: any) => socketInvoke('crm:getCampaignStats', params),
    getActivityStats: (params: any) => socketInvoke('crm:getActivityStats', params),
  },

  // ─── Analytics / Reporting ──────────────────────────────────────────
  analytics: {
    dashboardOverview:   (params: any) => socketInvoke('analytics:dashboardOverview', params),
    messageVolume:       (params: any) => socketInvoke('analytics:messageVolume', params),
    peakHours:           (params: any) => socketInvoke('analytics:peakHours', params),
    contactGrowth:       (params: any) => socketInvoke('analytics:contactGrowth', params),
    contactSegmentation: (params: any) => socketInvoke('analytics:contactSegmentation', params),
    campaignComparison:  (params: any) => socketInvoke('analytics:campaignComparison', params),
    friendRequests:      (params: any) => socketInvoke('analytics:friendRequests', params),
    workflowAnalytics:   (params: any) => socketInvoke('analytics:workflowAnalytics', params),
    aiAnalytics:         (params: any) => socketInvoke('analytics:aiAnalytics', params),
    responseTime:        (params: any) => socketInvoke('analytics:responseTime', params),
    labelUsage:          (params: any) => socketInvoke('analytics:labelUsage', params),
  },

  // ─── File ────────────────────────────────────────────────────────
  file: {
    openDialog: (options: any) => socketInvoke('file:openDialog', options),
    saveImage: (params: any) => socketInvoke('file:saveImage', params),
    getAppDataPath: () => socketInvoke('file:getAppDataPath'),
    openPath: (filePath: string) => socketInvoke('file:openPath', filePath),
    showItemInFolder: (filePath: string) => socketInvoke('file:showItemInFolder', filePath),
    saveAs: (params: any) => socketInvoke('file:saveAs', params),
    saveTempBlob: (params: any) => socketInvoke('file:saveTempBlob', params),
    getVideoMeta: (params: any) => socketInvoke('file:getVideoMeta', params),
    readImageAsBase64: (params: { localPath?: string; remoteUrl?: string }) => socketInvoke('file:readImageAsBase64', params),
    repairImage: (params: any) => socketInvoke('file:repairImage', params),
    validateLocalImages: (items: any) => socketInvoke('file:validateLocalImages', items),
    captureScreenshot: () => socketInvoke('file:captureScreenshot'),
    resolveMediaUrl: (bossUrl: string, mediaType?: string) => socketInvoke('media:resolveUrl', { bossUrl, mediaType }),
    hasMediaCache: (bossUrl: string) => socketInvoke('media:hasCache', { bossUrl }),
    preloadMediaBatch: (urls: string[]) => socketInvoke('media:preloadBatch', { urls }),
    ensureMediaLocal: (bossUrl: string, mediaType?: string) => socketInvoke('file:employeeEnsureMediaLocal', { bossUrl, mediaType }),
  },


  // ─── Workflow Engine ─────────────────────────────────────────────
    workflow: {
      list: () => socketInvoke('workflow:list'),
      get: (id: string) => socketInvoke('workflow:get', { id }),
      save: (workflow: any) => socketInvoke('workflow:save', { workflow }),
      delete: (id: string) => socketInvoke('workflow:delete', { id }),
      toggle: (id: string, enabled: boolean) => socketInvoke('workflow:toggle', { id, enabled }),
      runManual: (id: string, triggerData?: any) => socketInvoke('workflow:runManual', { id, triggerData }),
      getLogs: (id: string, limit?: number) => socketInvoke('workflow:getLogs', { id, limit }),
      deleteLogs: (id: string) => socketInvoke('workflow:deleteLogs', { id }),
      clone: (id: string, targetZaloId: string) => socketInvoke('workflow:clone', { id, targetZaloId }),
      cloneAll: (sourceZaloId: string, targetZaloId: string) => socketInvoke('workflow:cloneAll', { sourceZaloId, targetZaloId }),
      getWebhookUrl: (id: string) => socketInvoke('workflow:getWebhookUrl', { id }),
      regenerateWebhookToken: (id: string) => socketInvoke('workflow:regenerateWebhookToken', { id }),
      startTunnel: () => socketInvoke('workflow:startTunnel'),
      stopTunnel: () => socketInvoke('workflow:stopTunnel'),
      getTunnelStatus: () => socketInvoke('workflow:getTunnelStatus'),
      getPortConfig: () => socketInvoke('workflow:getPortConfig'),
      setPortConfig: (key: string, port: number) => socketInvoke('workflow:setPortConfig', { key, port }),
  },

  // ─── App-level (badge, open thread) ─────────────────────────────
  app: {
    setBadge: (count: number) => socketSend('app:setBadge', count),
    openThread: (params: { zaloId: string; threadId: string; threadType: number }) =>
      socketSend('app:openThread', params),
    sendBadgeImage: (params: { dataUrl: string; count: number }) =>
      socketSend('app:badgeImage', params),
    flashFrame: (active: boolean) => socketSend('app:flashFrame', { active }),
  },

  // ─── Auto-update ─────────────────────────────────────────────────
  update: {
    check:         () => socketSend('update:check'),
    download:      () => socketSend('update:download'),
    install:       () => socketSend('update:install'),
    rendererReady: () => socketSend('update:renderer-ready'),
  },

  // ─── Integration Hub ──────────────────────────────────────────────
  integration: {
    list:            () => socketInvoke('integration:list'),
    get:             (id: string) => socketInvoke('integration:get', { id }),
    save:            (integration: any) => socketInvoke('integration:save', { integration }),
    delete:          (id: string) => socketInvoke('integration:delete', { id }),
    toggle:          (id: string, enabled: boolean) => socketInvoke('integration:toggle', { id, enabled }),
    test:            (id: string) => socketInvoke('integration:test', { id }),
    execute:         (id: string, action: string, params?: any) => socketInvoke('integration:execute', { id, action, params }),
    executeByType:   (type: string, action: string, params?: any) => socketInvoke('integration:executeByType', { type, action, params }),
    getWebhookPort:  () => socketInvoke('integration:getWebhookPort'),
  },

  // ─── AI Assistants ────────────────────────────────────────────────
  ai: {
    listAssistants:  () => socketInvoke('ai:listAssistants'),
    getAssistant:    (id: string) => socketInvoke('ai:getAssistant', { id }),
    getDefault:      () => socketInvoke('ai:getDefault'),
    saveAssistant:   (assistant: any) => socketInvoke('ai:saveAssistant', { assistant }),
    deleteAssistant: (id: string) => socketInvoke('ai:deleteAssistant', { id }),
    testAssistant:   (id: string) => socketInvoke('ai:testAssistant', { id }),
    getFiles:        (assistantId: string) => socketInvoke('ai:getFiles', { assistantId }),
    uploadFile:      (assistantId: string, filePath: string) => socketInvoke('ai:uploadFile', { assistantId, filePath }),
    removeFile:      (fileId: number) => socketInvoke('ai:removeFile', { fileId }),
    suggest:         (assistantId: string, chatHistory: any[]) => socketInvoke('ai:suggest', { assistantId, chatHistory }),
    chat:            (assistantId: string, messages: any[], structured?: boolean, maxTokens?: number) => socketInvoke('ai:chat', { assistantId, messages, structured, maxTokens }),
    getAccountAssistant:  (zaloId: string, role: string) => socketInvoke('ai:getAccountAssistant', { zaloId, role }),
    setAccountAssistant:  (zaloId: string, role: string, assistantId: string | null) => socketInvoke('ai:setAccountAssistant', { zaloId, role, assistantId }),
    getAccountAssistants: (zaloId: string) => socketInvoke('ai:getAccountAssistants', { zaloId }),
    getUsageLogs:  (opts?: any) => socketInvoke('ai:getUsageLogs', opts || {}),
    getUsageStats: (opts?: any) => socketInvoke('ai:getUsageStats', opts || {}),
    // AI Conversations
    getOrCreateConversation: (params: any) => socketInvoke('ai:getOrCreateConversation', params),
    getConversationMessages: (params: any) => socketInvoke('ai:getConversationMessages', params),
    addConversationMessage:  (params: any) => socketInvoke('ai:addConversationMessage', params),
    getConversations:        (params: any) => socketInvoke('ai:getConversations', params),
    deleteConversation:      (params: any) => socketInvoke('ai:deleteConversation', params),
  },

  // ─── Tunnel ───────────────────────────────────────────────────────
  tunnel: {
    start:  () => socketInvoke('tunnel:start'),
    stop:   () => socketInvoke('tunnel:stop'),
    status: () => socketInvoke('tunnel:status'),
    getAll: () => socketInvoke('tunnel:getAll'),
  },

  // ─── Employee Management ───────────────────────────────────────────
  employee: {
    list:               () => socketInvoke('employee:list'),
    getById:            (employeeId: string) => socketInvoke('employee:getById', { employeeId }),
    create:             (params: any) => socketInvoke('employee:create', params),
    update:             (employeeId: string, updates: any) => socketInvoke('employee:update', { employeeId, updates }),
    delete:             (employeeId: string) => socketInvoke('employee:delete', { employeeId }),
    setPermissions:     (employeeId: string, permissions: any[]) => socketInvoke('employee:setPermissions', { employeeId, permissions }),
    getPermissions:     (employeeId: string) => socketInvoke('employee:getPermissions', { employeeId }),
    assignAccounts:     (employeeId: string, zaloIds: string[]) => socketInvoke('employee:assignAccounts', { employeeId, zaloIds }),
    getAssignedAccounts:(employeeId: string) => socketInvoke('employee:getAssignedAccounts', { employeeId }),
    getStats:           (employeeId: string, sinceTs?: number, untilTs?: number) => socketInvoke('employee:getStats', { employeeId, sinceTs, untilTs }),
    getSessions:        (employeeId: string, limit?: number) => socketInvoke('employee:getSessions', { employeeId, limit }),
    login:              (username: string, password: string) => socketInvoke('employee:login', { username, password }),
    validateToken:      (token: string) => socketInvoke('employee:validateToken', { token }),
    setMode:            (mode: string) => socketInvoke('employee:setMode', { mode }),
    getMode:            () => socketInvoke('employee:getMode'),
    connectToBoss:      (bossUrl: string, token: string) => socketInvoke('employee:connectToBoss', { bossUrl, token }),
    disconnectFromBoss: () => socketInvoke('employee:disconnectFromBoss'),
    getConnectionStatus:() => socketInvoke('employee:getConnectionStatus'),
    proxyAction:        (channel: string, params: any) => socketInvoke('employee:proxyAction', { channel, params }),
    // Groups
    listGroups:         () => socketInvoke('employee:listGroups'),
    createGroup:        (name: string, color?: string) => socketInvoke('employee:createGroup', { name, color }),
    updateGroup:        (groupId: string, updates: any) => socketInvoke('employee:updateGroup', { groupId, updates }),
    deleteGroup:        (groupId: string) => socketInvoke('employee:deleteGroup', { groupId }),
    // Analytics
    analyticsComparison:     (sinceTs: number, untilTs: number) => socketInvoke('employee:analytics:comparison', { sinceTs, untilTs }),
    analyticsMessageTimeline:(sinceTs: number, untilTs: number) => socketInvoke('employee:analytics:messageTimeline', { sinceTs, untilTs }),
    analyticsOnlineTimeline: (sinceTs: number, untilTs: number) => socketInvoke('employee:analytics:onlineTimeline', { sinceTs, untilTs }),
    analyticsResponseDist:   (sinceTs: number, untilTs: number) => socketInvoke('employee:analytics:responseDistribution', { sinceTs, untilTs }),
    analyticsHourlyActivity: (sinceTs: number, untilTs: number) => socketInvoke('employee:analytics:hourlyActivity', { sinceTs, untilTs }),
  },

  // ─── Workspace Management ────────────────────────────────────────
  workspace: {
    list:                 () => socketInvoke('workspace:list'),
    getActive:            () => socketInvoke('workspace:getActive'),
    create:               (params: any) => socketInvoke('workspace:create', params),
    update:               (id: string, updates: any) => socketInvoke('workspace:update', { id, updates }),
    delete:               (id: string) => socketInvoke('workspace:delete', { id }),
    switch:               (id: string) => socketInvoke('workspace:switch', { id }),
    isMulti:              () => socketInvoke('workspace:isMulti'),
    getDbPath:            (id: string) => socketInvoke('workspace:getDbPath', { id }),
    connectRemote:        (id: string, bossUrl: string, token: string) =>
                            socketInvoke('workspace:connectRemote', { id, bossUrl, token }),
    disconnectRemote:     (id: string) => socketInvoke('workspace:disconnectRemote', { id }),
    getConnectionStatus:  (id: string) => socketInvoke('workspace:getConnectionStatus', { id }),
    getAllStatuses:        () => socketInvoke('workspace:getAllStatuses'),
    loginRemote:          (bossUrl: string, username: string, password: string) =>
                            socketInvoke('workspace:loginRemote', { bossUrl, username, password }),
  },

  // ─── Relay Server (Boss) ──────────────────────────────────────────
  relay: {
    startServer:         (port?: number) => socketInvoke('relay:startServer', { port }),
    stopServer:          () => socketInvoke('relay:stopServer'),
    getServerStatus:     () => socketInvoke('relay:getServerStatus'),
    kickEmployee:        (employeeId: string) => socketInvoke('relay:kickEmployee', { employeeId }),
    startTunnel:         () => socketInvoke('relay:startTunnel'),
    stopTunnel:          () => socketInvoke('relay:stopTunnel'),
    getTunnelStatus:     () => socketInvoke('relay:getTunnelStatus'),
  },

  // ─── Facebook ─────────────────────────────────────────────────────
  fb: {
    addAccount:          (params: { cookie: string; proxyId?: number | null }) => socketInvoke('fb:addAccount', params),
    addAccountWithCredentials: (params: { username: string; password: string; twoFASecret?: string; proxyId?: number | null }) => socketInvoke('fb:addAccountWithCredentials', params),
    removeAccount:       (params: { accountId: string }) => socketInvoke('fb:removeAccount', params),
    updateCookie:        (params: { accountId: string; cookie: string }) => socketInvoke('fb:updateCookie', params),
    refreshProfile:      (params: { accountId: string }) => socketInvoke('fb:refreshProfile', params),
    getAccounts:         () => socketInvoke('fb:getAccounts'),
    connect:             (params: { accountId: string }) => socketInvoke('fb:connect', params),
    disconnect:          (params: { accountId: string }) => socketInvoke('fb:disconnect', params),
    checkHealth:         (params: { accountId: string }) => socketInvoke('fb:checkHealth', params),
    sendMessage:         (params: any) => socketInvoke('fb:sendMessage', params),
    sendAttachment:      (params: any) => socketInvoke('fb:sendAttachment', params),
    sendAttachments:     (params: any) => socketInvoke('fb:sendAttachments', params),
    unsendMessage:       (params: any) => socketInvoke('fb:unsendMessage', params),
    addReaction:         (params: any) => socketInvoke('fb:addReaction', params),
    getThreads:          (params: any) => socketInvoke('fb:getThreads', params),
    getMessages:         (params: any) => socketInvoke('fb:getMessages', params),
    markAsRead:          (params: any) => socketInvoke('fb:markAsRead', params),
    changeThreadName:    (params: any) => socketInvoke('fb:changeThreadName', params),
    changeThreadEmoji:   (params: any) => socketInvoke('fb:changeThreadEmoji', params),
    changeNickname:      (params: any) => socketInvoke('fb:changeNickname', params),
    loginWithCredentials:(params: any) => socketInvoke('fb:loginWithCredentials', params),    fetchThreadMessages:   (params: any) => socketInvoke('fb:fetchThreadMessages', params),
    refreshContactAvatar:  (params: any) => socketInvoke('fb:refreshContactAvatar', params),
    sendTyping:            (params: any) => socketInvoke('fb:sendTyping', params),
    blockUser:             (params: any) => socketInvoke('fb:blockUser', params),
    unblockUser:           (params: any) => socketInvoke('fb:unblockUser', params),
    forwardMessage:        (params: any) => socketInvoke('fb:forwardMessage', params),
    editMessage:           (params: any) => socketInvoke('fb:editMessage', params),
    createPoll:            (params: any) => socketInvoke('fb:createPoll', params),
    getUserInfoFacebookHtml: (params: { accountId: string; userId: string }) => socketInvoke('fb:getUserInfoFacebookHtml', params),
    // ─── Scan Data ────────────────────────────────────────────────
    scanGroupMembers:     (params: { accountId: string; groupId: string; cursor?: string | null }) => socketInvoke('fb:scanGroupMembers', params),
    scanGroupKeyword:     (params: { accountId: string; keyword: string; cursor?: string | null; filters?: string[]; bsid?: string; tsid?: string }) => socketInvoke('fb:scanGroupKeyword', params),
    scanFanpageKeyword:   (params: { accountId: string; keyword: string; cursor?: string | null; filters?: string[]; bsid?: string; tsid?: string }) => socketInvoke('fb:scanFanpageKeyword', params),
    scanPostTimeline:     (params: { accountId: string; sourceId: string; sourceType: 'profile' | 'fanpage' | 'group'; cursor?: string | null }) => socketInvoke('fb:scanPostTimeline', params),
    scanPostComments:     (params: { accountId: string; postId: string; cursor?: string | null }) => socketInvoke('fb:scanPostComments', params),
    scanPostKeyword:      (params: { accountId: string; keyword: string; cursor?: string | null; filters?: string[]; bsid?: string; tsid?: string }) => socketInvoke('fb:scanPostKeyword', params),
    // Batch
    scanGroupMembersBatch: (params: { accountId: string; groupIds: string[]; threadCount?: number }) => socketInvoke('fb:scanGroupMembersBatch', params),
    scanPostCommentsBatch: (params: { accountId: string; postIds: string[]; threadCount?: number }) => socketInvoke('fb:scanPostCommentsBatch', params),
    // Scan history
    saveScanLog:   (params: any) => socketInvoke('fb:saveScanLog', params),
    getScanLogs:   (params: { accountId: string; tabId?: string; limit?: number; offset?: number }) => socketInvoke('fb:getScanLogs', params),
    // Tab management
    scanSaveTab:       (params: any) => socketInvoke('fb:scanSaveTab', params),
    scanGetTabs:       (params: { accountId: string; status?: string; limit?: number; offset?: number }) => socketInvoke('fb:scanGetTabs', params),
    scanGetTab:        (params: { id: string }) => socketInvoke('fb:scanGetTab', params),
    scanUpdateTabStatus: (params: { id: string; status: string }) => socketInvoke('fb:scanUpdateTabStatus', params),
    scanTouchTab:       (params: { id: string }) => socketInvoke('fb:scanTouchTab', params),
    scanDeleteTab:     (params: { id: string }) => socketInvoke('fb:scanDeleteTab', params),
    scanSaveTabData:   (params: { tabId: string; items: any[]; pageInfo: any }) => socketInvoke('fb:scanSaveTabData', params),
    scanGetTabData:    (params: { tabId: string }) => socketInvoke('fb:scanGetTabData', params),
    scanSaveRequestLog:(params: any) => socketInvoke('fb:scanSaveRequestLog', params),
    scanGetRequestLogs:(params: { tabId: string; limit?: number; offset?: number }) => socketInvoke('fb:scanGetRequestLogs', params),
    scanGetStats:      (params: { accountId: string }) => socketInvoke('fb:scanGetStats', params),
    scanResetCache:() => socketInvoke('fb:scanResetCache'),
  },

  // ─── Telegram Bot ───────────────────────────────────────────────────────
  telegram: {
    validateBot:    (botToken: string) => socketInvoke('telegram:validateBot', botToken),
    startBot:       (account: any) => socketInvoke('telegram:startBot', account),
    stopBot:        (accountId: string) => socketInvoke('telegram:stopBot', accountId),
    isBotPolling:   (params: any) => socketInvoke('telegram:isBotPolling', params),
    sendMessage:    (params: any) => socketInvoke('telegram:sendMessage', params),
    sendPhoto:      (params: any) => socketInvoke('telegram:sendPhoto', params),
    sendVideo:      (params: any) => socketInvoke('telegram:sendVideo', params),
    sendDocument:   (params: any) => socketInvoke('telegram:sendDocument', params),
    sendAudio:      (params: any) => socketInvoke('telegram:sendAudio', params),
    forwardMessage: (params: any) => socketInvoke('telegram:forwardMessage', params),
    deleteMessage:  (params: any) => socketInvoke('telegram:deleteMessage', params),
    addReaction:    (params: any) => socketInvoke('telegram:addReaction', params),
    pinMessage:     (params: any) => socketInvoke('telegram:pinMessage', params),
    sendPoll:       (params: any) => socketInvoke('telegram:sendPoll', params),
    editMessage:    (params: any) => socketInvoke('telegram:editMessage', params),
    getActiveBots:  () => socketInvoke('telegram:getActiveBots'),
  },

  // ─── Telegram User (MTProto) ────────────────────────────────────────────
  telegramUser: {
    sendCode:       (phoneNumber: string) => socketInvoke('telegramUser:sendCode', phoneNumber),
    signIn:         (params: any) => socketInvoke('telegramUser:signIn', params),
    signIn2FA:      (password: string) => socketInvoke('telegramUser:signIn2FA', password),
    startListener:  (account: any) => socketInvoke('telegramUser:startListener', account),
    stopListener:   (accountId: string) => socketInvoke('telegramUser:stopListener', accountId),
    sendMessage:    (params: any) => socketInvoke('telegramUser:sendMessage', params),
    editMessage:    (params: any) => socketInvoke('telegramUser:editMessage', params),
    deleteMessages: (params: any) => socketInvoke('telegramUser:deleteMessages', params),
    forwardMessages:(params: any) => socketInvoke('telegramUser:forwardMessages', params),
    pinMessage:     (params: any) => socketInvoke('telegramUser:pinMessage', params),
    syncPinnedMessages: (params: any) => socketInvoke('telegramUser:syncPinnedMessages', params),
    ensureMessageAvailable: (params: any) => socketInvoke('telegramUser:ensureMessageAvailable', params),
    sendFile:       (params: any) => socketInvoke('telegramUser:sendFile', params),
    sendTopicFile:  (params: TelegramForumTopicContext & { filePath: string; caption?: string }) => socketInvoke('telegramUser:sendTopicFile', params),
    sendTyping:     (params: any) => socketInvoke('telegramUser:sendTyping', params),
    sendReaction:   (params: any) => socketInvoke('telegramUser:sendReaction', params),
    isConnected:    (accountId: string) => socketInvoke('telegramUser:isConnected', accountId),
    getActive:      () => socketInvoke('telegramUser:getActive'),
    refreshMessages:(params: { accountId: string }) => socketInvoke('telegramUser:refreshMessages', params),
    fetchSelfAvatar:(accountId: string) => socketInvoke('telegramUser:fetchSelfAvatar', accountId),
    // Group management
    getGroupInfo:      (params: any) => socketInvoke('telegramUser:getGroupInfo', params),
    joinGroup:         (params: any) => socketInvoke('telegramUser:joinGroup', params),
    getGroupMembers:   (params: any) => socketInvoke('telegramUser:getGroupMembers', params),
    hydrateMessageSenders: (params: any) => socketInvoke('telegramUser:hydrateMessageSenders', params),
    setDialogMute:     (params: any) => socketInvoke('telegramUser:setDialogMute', params),
    setDialogArchived: (params: any) => socketInvoke('telegramUser:setDialogArchived', params),
    setDialogPin:      (params: any) => socketInvoke('telegramUser:setDialogPin', params),
    getMessageReactions:(params: any) => socketInvoke('telegramUser:getMessageReactions', params),
    addChatUser:       (params: any) => socketInvoke('telegramUser:addChatUser', params),
    deleteChatUser:    (params: any) => socketInvoke('telegramUser:deleteChatUser', params),
    editChatTitle:     (params: any) => socketInvoke('telegramUser:editChatTitle', params),
    editChatPhoto:     (params: any) => socketInvoke('telegramUser:editChatPhoto', params),
    editChatAdmin:     (params: any) => socketInvoke('telegramUser:editChatAdmin', params),
    leaveChat:         (params: any) => socketInvoke('telegramUser:leaveChat', params),
    blockUser:         (params: any) => socketInvoke('telegramUser:blockUser', params),
    unblockUser:       (params: any) => socketInvoke('telegramUser:unblockUser', params),
    exportChatInvite:  (params: any) => socketInvoke('telegramUser:exportChatInvite', params),
    readChatHistory:   (params: any) => socketInvoke('telegramUser:readChatHistory', params),
    readForumTopic:    (params: any) => socketInvoke('telegramUser:readForumTopic', params),
    getMessages:       (params: any) => socketInvoke('telegramUser:getMessages', params),
    repairMessageMedia:(params: { accountId: string; chatId: string; messageId: string }) => socketInvoke('telegramUser:repairMessageMedia', params),
    repairEmptyMessages:(params: { accountId: string; chatId: string; messageIds: string[] }) => socketInvoke('telegramUser:repairEmptyMessages', params),
    repairMessageQuotes:(params: { accountId: string; chatId: string; items: Array<{ messageId: string; replyToId: string }> }) => socketInvoke('telegramUser:repairMessageQuotes', params),
    getFullChat:       (params: any) => socketInvoke('telegramUser:getFullChat', params),
    getUserProfile:    (params: any) => socketInvoke('telegramUser:getUserProfile', params),
    resolveUsername:   (params: any) => socketInvoke('telegramUser:resolveUsername', params),
    searchContacts:    (params: any) => socketInvoke('telegramUser:searchContacts', params),
    getPeers:          (params: any) => socketInvoke('telegramUser:getPeers', params),
    // Forum / Topics
    isForum:              (params: any) => socketInvoke('telegramUser:isForum', params),
    checkForumForNewGroups:(params: any) => socketInvoke('telegramUser:checkForumForNewGroups', params),
    getForumTopics:       (params: any) => socketInvoke('telegramUser:getForumTopics', params),
    getForumTopicMessages:(params: TelegramForumTopicContext & { limit?: number }) => socketInvoke('telegramUser:getForumTopicMessages', params),
    createForumTopic:     (params: any) => socketInvoke('telegramUser:createForumTopic', params),
    editForumTopic:       (params: TelegramForumTopicContext & { title?: string; iconEmojiId?: string; closed?: boolean; pinned?: boolean }) => socketInvoke('telegramUser:editForumTopic', params),
    sendTopicMessage:     (params: TelegramForumTopicContext & { text: string }) => socketInvoke('telegramUser:sendTopicMessage', params),
    // Sticker / GIF
    getStickerSets:       (params: any) => socketInvoke('telegramUser:getStickerSets', params),
    getStickerSetStickers:(params: any) => socketInvoke('telegramUser:getStickerSetStickers', params),
    getRecentStickers:    (params: any) => socketInvoke('telegramUser:getRecentStickers', params),
    getGifs:              (params: any) => socketInvoke('telegramUser:getGifs', params),
    searchGifs:           (params: any) => socketInvoke('telegramUser:searchGifs', params),
    sendSticker:          (params: any) => socketInvoke('telegramUser:sendSticker', params),
    sendGif:              (params: any) => socketInvoke('telegramUser:sendGif', params),
    downloadSticker:      (params: any) => socketInvoke('telegramUser:downloadSticker', params),
  },

  // ─── ERP ─────────────────────────────────────────────────────────
  erp: {
    // Projects
    projectList:        (params?: any) => socketInvoke('erp:project:list', params),
    projectCreate:      (params: any) => socketInvoke('erp:project:create', params),
    projectUpdate:      (params: any) => socketInvoke('erp:project:update', params),
    projectDelete:      (params: any) => socketInvoke('erp:project:delete', params),
    // Tasks
    taskList:           (params?: any) => socketInvoke('erp:task:list', params),
    taskGet:            (params: any) => socketInvoke('erp:task:get', params),
    taskCreate:         (params: any) => socketInvoke('erp:task:create', params),
    taskUpdate:         (params: any) => socketInvoke('erp:task:update', params),
    taskUpdateStatus:   (params: any) => socketInvoke('erp:task:updateStatus', params),
    taskAssign:         (params: any) => socketInvoke('erp:task:assign', params),
    taskDelete:         (params: any) => socketInvoke('erp:task:delete', params),
    taskAddChecklist:   (params: any) => socketInvoke('erp:task:addChecklist', params),
    taskToggleChecklist:(params: any) => socketInvoke('erp:task:toggleChecklist', params),
    taskAddComment:     (params: any) => socketInvoke('erp:task:addComment', params),
    taskEditComment:    (params: any) => socketInvoke('erp:task:editComment', params),
    taskDeleteComment:  (params: any) => socketInvoke('erp:task:deleteComment', params),
    taskListMyInbox:    (params: any) => socketInvoke('erp:task:listMyInbox', params),
    // Calendar
    calendarListEvents: (params: any) => socketInvoke('erp:calendar:listEvents', params),
    calendarCreate:     (params: any) => socketInvoke('erp:calendar:createEvent', params),
    calendarUpdate:     (params: any) => socketInvoke('erp:calendar:updateEvent', params),
    calendarDelete:     (params: any) => socketInvoke('erp:calendar:deleteEvent', params),
    calendarCheckConflict:(params: any) => socketInvoke('erp:calendar:checkConflict', params),
    // Notes
    noteListFolders:    (params: any) => socketInvoke('erp:note:listFolders', params),
    noteCreateFolder:   (params: any) => socketInvoke('erp:note:createFolder', params),
    noteRenameFolder:   (params: any) => socketInvoke('erp:note:renameFolder', params),
    noteDeleteFolder:   (params: any) => socketInvoke('erp:note:deleteFolder', params),
    noteList:           (params?: any) => socketInvoke('erp:note:list', params),
    noteGet:            (params: any) => socketInvoke('erp:note:get', params),
    noteCreate:         (params: any) => socketInvoke('erp:note:create', params),
    noteUpdate:         (params: any) => socketInvoke('erp:note:update', params),
    noteDelete:         (params: any) => socketInvoke('erp:note:delete', params),
    notePin:            (params: any) => socketInvoke('erp:note:pin', params),
    noteListTags:       () => socketInvoke('erp:note:listTags'),
    noteCreateTag:      (params: any) => socketInvoke('erp:note:createTag', params),
    noteAddTag:         (params: any) => socketInvoke('erp:note:addTag', params),
    noteRemoveTag:      (params: any) => socketInvoke('erp:note:removeTag', params),
    noteVersions:       (params: any) => socketInvoke('erp:note:versions', params),
    noteRestoreVersion: (params: any) => socketInvoke('erp:note:restoreVersion', params),
    noteShare:          (params: any) => socketInvoke('erp:note:share', params),
    noteListShares:     (params: any) => socketInvoke('erp:note:listShares', params),
    // Task watchers/dependencies (Phase 2)
    taskAddWatcher:     (params: any) => socketInvoke('erp:task:addWatcher', params),
    taskRemoveWatcher:  (params: any) => socketInvoke('erp:task:removeWatcher', params),
    taskAddDependency:  (params: any) => socketInvoke('erp:task:addDependency', params),
    taskRemoveDependency:(params: any) => socketInvoke('erp:task:removeDependency', params),
    // Calendar respond (Phase 2)
    calendarRespond:    (params: any) => socketInvoke('erp:calendar:respond', params),
    // HRM (Phase 2)
    departmentList:     () => socketInvoke('erp:department:list'),
    departmentCreate:   (params: any) => socketInvoke('erp:department:create', params),
    departmentUpdate:   (params: any) => socketInvoke('erp:department:update', params),
    departmentDelete:   (params: any) => socketInvoke('erp:department:delete', params),
    positionList:       () => socketInvoke('erp:position:list'),
    positionCreate:     (params: any) => socketInvoke('erp:position:create', params),
    positionUpdate:     (params: any) => socketInvoke('erp:position:update', params),
    positionDelete:     (params: any) => socketInvoke('erp:position:delete', params),
    employeeGetProfile: (params: any) => socketInvoke('erp:employee:getProfile', params),
    employeeUpdateProfile:(params: any) => socketInvoke('erp:employee:updateProfile', params),
    employeeListByDepartment:(params: any) => socketInvoke('erp:employee:listByDepartment', params),
    employeeDeleteProfile:(params: any) => socketInvoke('erp:employee:deleteProfile', params),
    attendanceCheckIn:  (params: any) => socketInvoke('erp:attendance:checkIn', params),
    attendanceCheckOut: (params: any) => socketInvoke('erp:attendance:checkOut', params),
    attendanceToday:    () => socketInvoke('erp:attendance:today'),
    attendanceList:     (params: any) => socketInvoke('erp:attendance:list', params),
    leaveCreate:        (params: any) => socketInvoke('erp:leave:create', params),
    leaveListMy:        () => socketInvoke('erp:leave:listMy'),
    leaveListPending:   () => socketInvoke('erp:leave:listPending'),
    leaveDecide:        (params: any) => socketInvoke('erp:leave:decide', params),
    leaveCancel:        (params: any) => socketInvoke('erp:leave:cancel', params),
    licenseSeatStatus:  () => socketInvoke('erp:license:seatStatus'),
    // Notifications
    notifyListInbox:    (params: any) => socketInvoke('erp:notify:listInbox', params),
    notifyMarkRead:     (params: any) => socketInvoke('erp:notify:markRead', params),
    notifyMarkAllRead:  (params: any) => socketInvoke('erp:notify:markAllRead', params),
    notifyUnreadCount:  (params: any) => socketInvoke('erp:notify:unreadCount', params),
    notifyDelete:       (params: any) => socketInvoke('erp:notify:delete', params),
    notifyDeleteAll:    (params: any) => socketInvoke('erp:notify:deleteAll', params),
  },
  lockScreen: {
    status:           () => socketInvoke('lockScreen:status'),
    setup:            (params: { password: string }) => socketInvoke('lockScreen:setup', params),
    verify:           (params: { password: string }) => socketInvoke('lockScreen:verify', params),
    verifyRecovery:   (params: { recoveryKey: string }) => socketInvoke('lockScreen:verifyRecovery', params),
    changePassword:   (params: { oldPassword: string; newPassword: string }) => socketInvoke('lockScreen:changePassword', params),
    resetPassword:    (params: { recoveryKey: string; newPassword: string }) => socketInvoke('lockScreen:resetPassword', params),
    disable:          (params: { password: string }) => socketInvoke('lockScreen:disable', params),
    getRecoveryKey:   (params: { password: string }) => socketInvoke('lockScreen:getRecoveryKey', params),
    setBiometric:     (params: { enabled: boolean }) => socketInvoke('lockScreen:setBiometric', params),
    biometricUnlock:  () => socketInvoke('lockScreen:biometricUnlock'),
  },

  // ─── Media Library ───────────────────────────────────────────────
  library: {
    getItems:    (params: any) => socketInvoke('library:getItems', params),
    upload:      (params: any) => socketInvoke('library:upload', params),
    deleteItem:  (uuid: string) => socketInvoke('library:deleteItem', uuid),
    getFolders:  (params: { zaloId: string; type?: string }) => socketInvoke('library:getFolders', params),
    createFolder:(params: any) => socketInvoke('library:createFolder', params),
    updateItem:  (uuid: string, params: any) => socketInvoke('library:updateItem', { uuid, ...params }),
    renameFolder:(id: number, name: string) => socketInvoke('library:renameFolder', { id, name }),
    deleteFolder:(id: number) => socketInvoke('library:deleteFolder', id),
  },
  on: (channel: string, callback: (...args: any[]) => void) => {
    socketOn(channel, callback);
    return () => socketOff(channel, callback);
  },

  removeAllListeners: (channel: string) => {
    socketOff(channel);
  },

  // ─── Proxy ───────────────────────────────────────────────────────────────
  proxy: {
    list:          ()                              => socketInvoke('proxy:list'),
    save:          (proxy: any)                    => socketInvoke('proxy:save', { proxy }),
    update:        (id: number, proxy: any)        => socketInvoke('proxy:update', { id, proxy }),
    delete:        (id: number)                    => socketInvoke('proxy:delete', { id }),
    setAccount:    (zaloId: string, proxyId: number | null) => socketInvoke('proxy:setAccount', { zaloId, proxyId }),
    getForAccount: (zaloId: string)                => socketInvoke('proxy:getForAccount', { zaloId }),
    test:          (proxy: any)                    => socketInvoke('proxy:test', { proxy }),
  },
};
}